CREATE TABLE clientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nit VARCHAR(20) NOT NULL,
  instalacion_id VARCHAR(100),
  estado VARCHAR(20), -- activo / demo / bloqueado
  fecha_activacion TIMESTAMP,
  fecha_expiracion TIMESTAMP,
  dias_demo INTEGER
);
