unit DianUnits;

interface

uses
  System.Generics.Collections,
  System.SysUtils;

type
  TDianUnits = class
  private
    class var FUnitMap: TDictionary<string, string>;
    class procedure AddSafe(const ACode, AName: string);
    class procedure PopulatePart1;
    class procedure PopulatePart2;
    class procedure PopulatePart3;
    class procedure PopulatePart4;
    class procedure PopulatePart5;
    class procedure PopulatePart6;
    class procedure PopulatePart7;
    class procedure PopulatePart8;
    class procedure PopulatePart9;
    class procedure PopulatePart10;
  public
    class constructor Create;
    class destructor Destroy;
    class function GetUnitName(const ACode: string): string;
  end;

implementation

{ TDianUnits }

class constructor TDianUnits.Create;
begin
  FUnitMap := TDictionary<string, string>.Create;
  PopulatePart1;
  PopulatePart2;
  PopulatePart3;
  PopulatePart4;
  PopulatePart5;
  PopulatePart6;
  PopulatePart7;
  PopulatePart8;
  PopulatePart9;
  PopulatePart10;
end;

class destructor TDianUnits.Destroy;
begin
  FUnitMap.Free;
end;

class procedure TDianUnits.AddSafe(const ACode, AName: string);
begin
  if not FUnitMap.ContainsKey(ACode) then
    FUnitMap.Add(ACode, AName)
  else
    WriteLn('[DianUnits] Error: Duplicate unit code detected: ' + ACode);
end;

class function TDianUnits.GetUnitName(const ACode: string): string;
begin
  if not FUnitMap.TryGetValue(ACode, Result) then
  begin
    WriteLn('[DianUnits] Warning: Missing unit code: ' + ACode);
    Result := ACode;
  end;
end;

class procedure TDianUnits.PopulatePart1;
begin
  AddSafe('04', 'spray pequeÃ±o');
  AddSafe('05', 'levantar');
  AddSafe('08', 'Lote calor');
  AddSafe('10', 'grupo');
  AddSafe('11', 'equipar');
  AddSafe('13', 'raciÃ³n');
  AddSafe('14', 'Disparo');
  AddSafe('15', 'palo');
  AddSafe('16', 'tambor de ciento quince kg');
  AddSafe('17', 'tambor de cien libras');
  AddSafe('18', 'tambor de cincuenta y cinco galones (US)');
  AddSafe('19', 'camiÃ³n cisterna');
  AddSafe('20', 'contenedor de veinte pies');
  AddSafe('21', 'contenedor de cuarenta pies');
  AddSafe('22', 'decilitro por gramo');
  AddSafe('23', 'gramo por centÃ­metro cÃºbico');
  AddSafe('24', 'libra teÃ³rica');
  AddSafe('25', 'gramo por centÃ­metro cuadrado');
  AddSafe('26', 'tonelada real');
  AddSafe('27', 'tonelada teÃ³rica');
  AddSafe('28', 'kilogramo por metro cuadrado');
  AddSafe('29', 'libra por mil pies cuadrados');
  AddSafe('30', 'DÃ­a de potencia del caballo por tonelada mÃ©trica seca al aire.');
  AddSafe('31', 'coger peso');
  AddSafe('32', 'kilogramo por aire seco tonelada mÃ©trica');
  AddSafe('33', 'kilopascales metros cuadrados por gramo');
  AddSafe('34', 'kilopascales por milÃ­metro');
  AddSafe('35', 'mililitros por centÃ­metro cuadrado segundo');
  AddSafe('36', 'pies cÃºbicos por minuto por pie cuadrado');
  AddSafe('37', 'onza por pie cuadrado');
  AddSafe('38', 'onzas por pie cuadrado por 0,01 pulgadas');
  AddSafe('40', 'mililitro por segundo');
  AddSafe('41', 'mililitro por minuto');
  AddSafe('43', 'bolsa sÃºper a granel');
  AddSafe('44', 'bolsa a granel de quinientos kg');
  AddSafe('45', 'bolsa a granel de trescientos kg');
  AddSafe('46', 'bolsa a granel de cincuenta libras');
  AddSafe('47', 'bolsa de cincuenta libras');
  AddSafe('48', 'carga de automÃ³viles a granel');
  AddSafe('53', 'kilogramos teÃ³ricos');
  AddSafe('54', 'tonelada teÃ³rica');
  AddSafe('56', 'sitas');
  AddSafe('57', 'malla');
  AddSafe('58', 'kilogramo neto');
  AddSafe('59', 'parte por millÃ³n');
  AddSafe('60', 'porcentaje de peso');
  AddSafe('61', 'parte por billÃ³n (US)');
  AddSafe('62', 'porcentaje por 1000 horas');
  AddSafe('63', 'tasa de fracaso en el tiempo');
  AddSafe('64', 'libra por pulgada cuadrada, calibre');
  AddSafe('66', 'Oersted');
  AddSafe('69', 'prueba de escala especÃ­fica');
  AddSafe('71', 'voltio amperio por libra');
  AddSafe('72', 'vatio por libra');
  AddSafe('73', 'amperio tum por centÃ­metro');
  AddSafe('74', 'milipascal');
  AddSafe('76', 'gauss');
  AddSafe('77', 'mili pulgadas');
  AddSafe('78', 'kilogauss');
  AddSafe('80', 'libras por pulgada cuadrada absoluta');
  AddSafe('81', 'Enrique');
  AddSafe('84', 'kilopound por pulgada cuadrada');
  AddSafe('85', 'fuerza libra pie');
  AddSafe('87', 'libra por pie cÃºbico');
  AddSafe('89', 'equilibrio');
  AddSafe('90', 'Saybold segundo universal');
  AddSafe('91', 'alimenta');
  AddSafe('92', 'calorÃ­as por centÃ­metro cÃºbico');
  AddSafe('93', 'calorÃ­as por gramo');
  AddSafe('94', 'unidad');
  AddSafe('95', 'veinte mil galones (US) de carros');
  AddSafe('96', 'diez mil galones (US) de carros');
  AddSafe('97', 'tambor de diez kg');
  AddSafe('98', 'tambor de quince kg');
  AddSafe('1Âª', 'milla de coche');
  AddSafe('1B', 'recuento de coches');
  AddSafe('1C', 'recuento de locomotoras');
  AddSafe('1D', 'recuento de cabos');
  AddSafe('1E', 'carro vacio');
  AddSafe('1F', 'millas de tren');
  AddSafe('1G', 'uso de combustible galÃ³n (US)');
  AddSafe('1H', 'milla del caboose');
  AddSafe('1I', 'tipo de interÃ©s fijo');
  AddSafe('1J', 'tonelada milla');
  AddSafe('1K', 'milla locomotora');
  AddSafe('1L', 'recuento total de coches');
  AddSafe('1M', 'milla de coche total');
  AddSafe('1X', 'cuarto de milla');
  AddSafe('2Âª', 'radianes por segundo');
  AddSafe('2B', 'radianes por segundo al cuadrado');
  AddSafe('2C', 'RÃ¶ntgen');
  AddSafe('2I', 'Unidad tÃ©rmica britÃ¡nica por hora.');
  AddSafe('2J', 'centÃ­metro cÃºbico por segundo');
  AddSafe('2K', 'pie cÃºbico por hora');
  AddSafe('2L', 'pie cÃºbico por minuto');
  AddSafe('2M', 'centÃ­metro por segundo');
  AddSafe('2N', 'decibel');
  AddSafe('2P', 'kilobyte');
end;

class procedure TDianUnits.PopulatePart2;
begin
  AddSafe('2Q', 'kilobecquerel');
  AddSafe('2R', 'kilocurie');
  AddSafe('2U', 'megagramo');
  AddSafe('2V', 'megagramo por hora');
  AddSafe('2W', 'compartimiento');
  AddSafe('2X', 'metro por minuto');
  AddSafe('2Y', 'millirÃ¶ntgen');
  AddSafe('2Z', 'milivoltios');
  AddSafe('3B', 'megajulio');
  AddSafe('3C', 'manmonth');
  AddSafe('3E', 'libra por libra de producto');
  AddSafe('3G', 'libra por pieza de producto');
  AddSafe('3H', 'kilogramo por kilogramo de producto');
  AddSafe('3I', 'kilogramo por pieza de producto');
  AddSafe('4Âª', 'bobina');
  AddSafe('4B', 'gorra');
  AddSafe('4C', 'centistokes');
  AddSafe('4E', 'paquete de veinte');
  AddSafe('4G', 'microlitro');
  AddSafe('4H', 'micrometro');
  AddSafe('4K', 'miliamperio');
  AddSafe('4L', 'megabyte');
  AddSafe('4M', 'miligramo por hora');
  AddSafe('4N', 'megabecquerel');
  AddSafe('4Âº', 'microfarad');
  AddSafe('4P', 'newton por metro');
  AddSafe('4Q', 'onza pulgada');
  AddSafe('4R', 'pie onza');
  AddSafe('4T', 'picofarad');
  AddSafe('4U', 'libra por hora');
  AddSafe('4W', 'tonelada (US) por hora');
  AddSafe('4X', 'kilolitro por hora');
  AddSafe('5Âª', 'barril por minuto');
  AddSafe('5B', 'lote');
  AddSafe('5C', 'galÃ³n (US) por mil');
  AddSafe('5E', 'MMSCF / dÃ­a');
  AddSafe('5F', 'libras por mil');
  AddSafe('5G', 'bomba');
  AddSafe('5H', 'escenario');
  AddSafe('5I', 'pie cÃºbico estÃ¡ndar');
  AddSafe('5J', 'potencia hidrÃ¡ulica de caballos');
  AddSafe('5K', 'contar por minuto');
  AddSafe('5P', 'nivel sismico');
  AddSafe('5Q', 'nfor sismica');
  AddSafe('A1', '15 calorÃ­as C');
  AddSafe('A10', 'amperio metro cuadrado por joule segundo');
  AddSafe('A11', 'Ã Â¥ ngstrÃ¶m');
  AddSafe('A12', 'unidad astronÃ³mica');
  AddSafe('A13', 'attojoule');
  AddSafe('A14', 'granero');
  AddSafe('A15', 'granero por electrÃ³n voltio');
  AddSafe('A16', 'granero por voltio de electrones esteradiano,');
  AddSafe('A17', 'granero por sterdian');
  AddSafe('A18', 'becquerel por kilogramo');
  AddSafe('A19', 'becquerel por metro cÃºbico');
  AddSafe('A2', 'amperio por centÃ­metro');
  AddSafe('A20', 'Unidad tÃ©rmica britÃ¡nica por segundo pie cuadrado grado Rankin');
  AddSafe('A21', 'Unidad tÃ©rmica britÃ¡nica por libra grado Rankin');
  AddSafe('A22', 'Unidad tÃ©rmica britÃ¡nica por segundo pie grado Rankin');
  AddSafe('A23', 'Unidad tÃ©rmica britÃ¡nica por hora pie cuadrado grado Rankin');
  AddSafe('A24', 'candela por metro cuadrado');
  AddSafe('A25', 'cheval vapeur');
  AddSafe('A26', 'medidor de culombio');
  AddSafe('A27', 'medidor de culombio al cuadrado por voltio');
  AddSafe('A28', 'Coulomb por centÃ­metro cÃºbico');
  AddSafe('A29', 'Coulomb por metro cÃºbico');
  AddSafe('A3', 'amperio por milÃ­metro');
  AddSafe('A30', 'Coulomb por milÃ­metro cÃºbico');
  AddSafe('A31', 'Coulomb por kilogramo segundo');
  AddSafe('A32', 'Coulomb por mol');
  AddSafe('A33', 'Coulomb por centÃ­metro cuadrado');
  AddSafe('A34', 'Coulomb por metro cuadrado');
  AddSafe('A35', 'Coulomb por milÃ­metro cuadrado');
  AddSafe('A36', 'centÃ­metro cÃºbico por mol');
  AddSafe('A37', 'nformaci cÃºbico por mol');
  AddSafe('A38', 'metro cÃºbico por coulomb');
  AddSafe('A39', 'metro cÃºbico por kilogramo');
  AddSafe('A4', 'amperio por centÃ­metro cuadrado');
  AddSafe('A40', 'metro cÃºbico por mol');
  AddSafe('A41', 'amperio por metro cuadrado');
  AddSafe('A42', 'curie por kilogramo');
  AddSafe('A43', 'tonelaje de peso muerto');
  AddSafe('A44', 'decalitro');
  AddSafe('A45', 'decÃ¡metro');
  AddSafe('A47', 'decitex');
  AddSafe('A48', 'grado Rankin');
  AddSafe('A49', 'negador');
  AddSafe('A5', 'amperio metro cuadrado');
  AddSafe('A50', 'dyn segundo por centÃ­metro cÃºbico');
  AddSafe('A51', 'dina segundo por centÃ­metro');
  AddSafe('A52', 'dina segundo por centÃ­metro al quinto');
  AddSafe('A53', 'electronvolt');
  AddSafe('A54', 'electronvoltio por metro');
  AddSafe('A55', 'metro electronvolt cuadrado');
  AddSafe('A56', 'electronvoltio de metro cuadrado por kilogramo');
  AddSafe('A57', 'ergio');
  AddSafe('A58', 'erg por centÃ­metro');
end;

class procedure TDianUnits.PopulatePart3;
begin
  AddSafe('A6', 'amperio por metro cuadrado kelvin al cuadrado');
  AddSafe('A60', 'erg por centÃ­metro cÃºbico');
  AddSafe('A61', 'erg por gramo');
  AddSafe('A62', 'erg por gramo de segundo');
  AddSafe('A63', 'erg por segundo');
  AddSafe('A64', 'erg por segundo centÃ­metro cuadrado');
  AddSafe('A65', 'erg por centÃ­metro cuadrado segundo');
  AddSafe('A66', 'erg centÃ­metro cuadrado');
  AddSafe('A67', 'ergÃ­metro cuadrado por gramo');
  AddSafe('A68', 'exajulio');
  AddSafe('A69', 'faradio por metro');
  AddSafe('A7', 'amperio por milÃ­metro cuadrado');
  AddSafe('A70', 'femtojoule');
  AddSafe('A71', 'femtometro');
  AddSafe('A73', 'pie por segundo al cuadrado');
  AddSafe('A74', 'pie-fuerza de la libra por segundo');
  AddSafe('A75', 'tonelada de carga');
  AddSafe('A76', 'galÃ³n');
  AddSafe('A77', 'Unidad de desplazamiento CGS gaussiana');
  AddSafe('A78', 'Unidad gaussiana CGS de corriente elÃ©ctrica.');
  AddSafe('A79', 'Unidad Gaussian CGS de carga elÃ©ctrica.');
  AddSafe('A8', 'amperio segundo');
  AddSafe('A80', 'Unidad Gaussian CGS de intensidad de campo elÃ©ctrico.');
  AddSafe('A81', 'Unidad Gaussian CGS de polarizaciÃ³n elÃ©ctrica.');
  AddSafe('A82', 'Unidad Gaussian CGS de potencial elÃ©ctrico.');
  AddSafe('A83', 'Unidad Gaussiana CGS de magnetizaciÃ³n.');
  AddSafe('A84', 'gigacoulomb por metro cÃºbico');
  AddSafe('A85', 'Gigaelectronvolt');
  AddSafe('A86', 'gigahercios');
  AddSafe('A87', 'gigaohm');
  AddSafe('A88', 'medidor de gigaohm');
  AddSafe('A89', 'gigapascal');
  AddSafe('A9', 'tarifa');
  AddSafe('A90', 'gigavatios');
  AddSafe('A91', 'gon');
  AddSafe('A93', 'gramo por metro cÃºbico');
  AddSafe('A94', 'gramo por mol');
  AddSafe('A95', 'gris');
  AddSafe('A96', 'gris por segundo');
  AddSafe('A97', 'hectopascal');
  AddSafe('A98', 'Henry por metro');
  AddSafe('AA', 'bola');
  AddSafe('AB', 'paquete a granel');
  AddSafe('ACR', 'acre');
  AddSafe('AD', 'byte');
  AddSafe('AE', 'amperio por metro');
  AddSafe('AH', 'minuto adicional');
  AddSafe('AI', 'minuto promedio por llamada');
  AddSafe('AJ', 'policÃ­a');
  AddSafe('AK', 'braza');
  AddSafe('AL', 'nfor de acceso');
  AddSafe('AM', 'ampolla');
  AddSafe('AMH', 'hora amperio');
  AddSafe('AMP', 'amperio');
  AddSafe('ANA', 'aÃ±o');
  AddSafe('AP', 'solo libra de aluminio');
  AddSafe('APZ', 'onza troy o onza de boticarios');
  AddSafe('AQ', 'Unidad de factor antihemofÃ­lico (AHF)');
  AddSafe('AR', 'supositorio');
  AddSafe('SON', 'son');
  AddSafe('COMO', 'surtido');
  AddSafe('ASM', 'fuerza alcohÃ³lica en masa');
  AddSafe('ASU', 'fuerza alcohÃ³lica por volumen');
  AddSafe('ATM', 'ambiente estÃ¡ndar');
  AddSafe('ATT', 'ambiente tÃ©cnico');
  AddSafe('AV', 'cÃ¡psula');
  AddSafe('AW', 'vial lleno de polvo');
  AddSafe('SÃ', 'montaje');
  AddSafe('AZ', 'Unidad tÃ©rmica britÃ¡nica por libra');
  AddSafe('B0', 'Btu por pie cÃºbico');
  AddSafe('B1', 'barril (US) por dÃ­a');
  AddSafe('B11', 'julios por kilogramo kelvin');
  AddSafe('B12', 'julios por metro');
  AddSafe('B13', 'julios por metro cuadrado');
  AddSafe('B14', 'julios por metro a la cuarta potencia');
  AddSafe('B15', 'julios por mol');
  AddSafe('B16', 'julios por mol kelvin');
  AddSafe('B18', 'joule segundo');
  AddSafe('B2', 'litera');
  AddSafe('B20', 'joule metro cuadrado por kilogramo');
  AddSafe('B21', 'kelvin por vatio');
  AddSafe('B22', 'Kiloampere');
  AddSafe('B23', 'kiloampere por metro cuadrado');
  AddSafe('B24', 'kiloampere por metro');
  AddSafe('B25', 'kilobecquerel por kilogramo');
  AddSafe('B26', 'kilocoulomb');
  AddSafe('B27', 'kilocoulomb por metro cÃºbico');
  AddSafe('B28', 'kilocoulomb por metro cuadrado');
  AddSafe('B29', 'kiloelectronvolt');
  AddSafe('B3', 'libra de bateo');
end;

class procedure TDianUnits.PopulatePart4;
begin
  AddSafe('B31', 'kilogramo metro por segundo');
  AddSafe('B32', 'kilogramo metro cuadrado');
  AddSafe('B33', 'kilogramo metro cuadrado por segundo');
  AddSafe('B34', 'kilogramo por decÃ­metro cÃºbico');
  AddSafe('B35', 'kilogramo por litro');
  AddSafe('B36', 'calorÃ­a termoquÃ­mica por gramo');
  AddSafe('B37', 'kilogramo de fuerza');
  AddSafe('B38', 'metro de fuerza de kilogramo');
  AddSafe('B39', 'metro de fuerza de kilogramo por segundo');
  AddSafe('B4', 'barril, imperial');
  AddSafe('B40', 'kilogramo de fuerza por metro cuadrado');
  AddSafe('B41', 'kilojoule per kelvin');
  AddSafe('B42', 'kilojoule por kilogramo');
  AddSafe('B43', 'kilojoule por kilogramo kelvin');
  AddSafe('B44', 'kilojoule por mol');
  AddSafe('B45', 'kilomol');
  AddSafe('B46', 'kilomol por metro cÃºbico');
  AddSafe('B47', 'Kilonewton');
  AddSafe('B48', 'medidor de kilonewton');
  AddSafe('B49', 'kiloohm');
  AddSafe('B5', 'palanquilla');
  AddSafe('B50', 'medidor de kiloohm');
  AddSafe('B51', 'kilopond');
  AddSafe('B52', 'kilosegundo');
  AddSafe('B53', 'kilosiemens');
  AddSafe('B54', 'kilosiemens por metro');
  AddSafe('B55', 'kilovoltios por metro');
  AddSafe('B56', 'kiloveber por metro');
  AddSafe('B57', 'aÃ±o luz');
  AddSafe('B58', 'litro por mol');
  AddSafe('B59', 'hora lumen');
  AddSafe('B6', 'bollo');
  AddSafe('B60', 'lumen por metro cuadrado');
  AddSafe('B61', 'lumen por vatio');
  AddSafe('B62', 'lumen segundo');
  AddSafe('B63', 'hora de lux');
  AddSafe('B64', 'lux segundo');
  AddSafe('B65', 'Maxwell');
  AddSafe('B66', 'megaamperios por metro cuadrado');
  AddSafe('B67', 'megabecquerel por kilogramo');
  AddSafe('B69', 'megacoulomb por metro cÃºbico');
  AddSafe('B7', 'ciclo');
  AddSafe('B70', 'megacoulomb por metro cuadrado');
  AddSafe('B71', 'megaelectronvolt');
  AddSafe('B72', 'megagramo por metro cÃºbico');
  AddSafe('B73', 'meganewton');
  AddSafe('B74', 'medidor de meganewton');
  AddSafe('B75', 'megaohm');
  AddSafe('B76', 'metro megaohm');
  AddSafe('B77', 'megasiemens por metro');
  AddSafe('B78', 'megavoltio');
  AddSafe('B79', 'megavolt por metro');
  AddSafe('B8', 'julios por metro cÃºbico');
  AddSafe('B81', 'metro recÃ­proco cuadrado recÃ­proco segundo');
  AddSafe('B83', 'metro a la cuarta potencia');
  AddSafe('B84', 'microamperios');
  AddSafe('B85', 'microbar');
  AddSafe('B86', 'microcoulomb');
  AddSafe('B87', 'microcoulomb por metro cÃºbico');
  AddSafe('B88', 'microcoulomb por metro cuadrado');
  AddSafe('B89', 'microfarada por metro');
  AddSafe('B9', 'batt');
  AddSafe('B90', 'microhenry');
  AddSafe('B91', 'microhenry por metro');
  AddSafe('B92', 'micronewton');
  AddSafe('B93', 'medidor de micronewton');
  AddSafe('B94', 'microohm');
  AddSafe('B95', 'medidor de microohmios');
  AddSafe('B96', 'micropascal');
  AddSafe('B97', 'microradiano');
  AddSafe('B98', 'microsegundo');
  AddSafe('B99', 'microsiemens');
  AddSafe('BAR', 'bar');
  AddSafe('BB', 'caja base');
  AddSafe('BD', 'tablero');
  AddSafe('SER', 'haz');
  AddSafe('BFT', 'pie de tabla');
  AddSafe('BG', 'bolso');
  AddSafe('BH', 'cepillo');
  AddSafe('BHP', 'potencia al freno');
  AddSafe('BIL', 'trillÃ³n de dÃ³lares');
  AddSafe('BJ', 'cangilÃ³n');
  AddSafe('BK', 'cesta');
  AddSafe('BL', 'bala');
  AddSafe('BLD', 'barril seco');
  AddSafe('BLL', 'barril (EE. UU.) (petrÃ³leo, etc.)');
  AddSafe('BO', 'botella');
  AddSafe('BP', 'cien pies de tabla');
  AddSafe('BQL', 'becquerel');
end;

class procedure TDianUnits.PopulatePart5;
begin
  AddSafe('BR', 'bar');
  AddSafe('BT', 'tornillo');
  AddSafe('BTU', 'Unidad TÃ©rmica BritÃ¡nica');
  AddSafe('BUA', 'bushel (EE. UU.)');
  AddSafe('BUI', 'bushel (Reino Unido)');
  AddSafe('BW', 'peso base');
  AddSafe('BX', 'caja');
  AddSafe('BZ', 'millones de BTUs');
  AddSafe('C0', 'llamada');
  AddSafe('C1', 'producto compuesto libra (peso total)');
  AddSafe('C10', 'millifarad');
  AddSafe('C11', 'miligal');
  AddSafe('C12', 'miligramo por metro');
  AddSafe('C13', 'miligray');
  AddSafe('C14', 'milihenry');
  AddSafe('C15', 'milijoule');
  AddSafe('C16', 'milÃ­metro por segundo');
  AddSafe('C17', 'milÃ­metro cuadrado por segundo');
  AddSafe('C18', 'milimol');
  AddSafe('C19', 'mol por kilogramo');
  AddSafe('C2', 'carset');
  AddSafe('C20', 'millinewton');
  AddSafe('C22', 'millinewton por metro');
  AddSafe('C23', 'medidor de miliohm');
  AddSafe('C24', 'segundo milipascal');
  AddSafe('C25', 'miliradian');
  AddSafe('C26', 'milisegundo');
  AddSafe('C27', 'milisiemens');
  AddSafe('C28', 'milisievert');
  AddSafe('C29', 'millitesla');
  AddSafe('C3', 'microvoltios por metro');
  AddSafe('C30', 'milivoltios por metro');
  AddSafe('C31', 'milivatios');
  AddSafe('C32', 'milivatios por metro cuadrado');
  AddSafe('C33', 'milliweber');
  AddSafe('C34', 'Topo');
  AddSafe('C35', 'mol por decÃ­metro cÃºbico');
  AddSafe('C36', 'mol por metro cÃºbico');
  AddSafe('C38', 'mol por litro');
  AddSafe('C39', 'Nanoampere');
  AddSafe('C4', 'partido de carga');
  AddSafe('C40', 'nanocoulomb');
  AddSafe('C41', 'nanofarad');
  AddSafe('C42', 'nanofarad por metro');
  AddSafe('C43', 'nanohenry');
  AddSafe('C44', 'nanohenry por metro');
  AddSafe('C45', 'nanometro');
  AddSafe('C46', 'medidor de nanoohm');
  AddSafe('C47', 'nanosegundo');
  AddSafe('C48', 'nanotesla');
  AddSafe('C49', 'nanovatio');
  AddSafe('C5', 'costo');
  AddSafe('C50', 'neper');
  AddSafe('C51', 'neper por segundo');
  AddSafe('C52', 'picometro');
  AddSafe('C53', 'metro de newton segundo');
  AddSafe('C54', 'newton metro cuadrado kilogramo cuadrado');
  AddSafe('C55', 'newton por metro cuadrado');
  AddSafe('C56', 'newton por milÃ­metro cuadrado');
  AddSafe('C57', 'newton segundo');
  AddSafe('C58', 'newton segundo por metro');
  AddSafe('C59', 'octava');
  AddSafe('C6', 'cÃ©lula');
  AddSafe('C60', 'ohm centÃ­metro');
  AddSafe('C61', 'ohm metro');
  AddSafe('C62', 'uno');
  AddSafe('C63', 'parsec');
  AddSafe('C64', 'pascal por kelvin');
  AddSafe('C65', 'segundo pascal');
  AddSafe('C66', 'segundo pascal por metro cÃºbico');
  AddSafe('C67', 'segundo pascal por metro');
  AddSafe('C68', 'petajoule');
  AddSafe('C69', 'telefono');
  AddSafe('C7', 'centipoise');
  AddSafe('C70', 'picoampere');
  AddSafe('C71', 'picocoulomb');
  AddSafe('C72', 'picofarad por metro');
  AddSafe('C73', 'picohenry');
  AddSafe('C75', 'picowatt');
  AddSafe('C76', 'picowatt por metro cuadrado');
  AddSafe('C77', 'medidor de libras');
  AddSafe('C78', 'fuerza de libra');
  AddSafe('C8', 'Millicoulomb por kilogramo');
  AddSafe('C80', 'rad');
  AddSafe('C81', 'radiÃ¡n');
  AddSafe('C82', 'medidor de radianes al cuadrado por mol');
  AddSafe('C83', 'medidor de radianes al cuadrado por kilogramo');
  AddSafe('C84', 'radian por metro');
  AddSafe('C85', 'Ã¢ â¬ ngstr recÃ­proco "m');
  AddSafe('C86', 'metro cÃºbico recÃ­proco');
  AddSafe('C87', 'metro cÃºbico recÃ­proco por segundo');
end;

class procedure TDianUnits.PopulatePart6;
begin
  AddSafe('C88', 'voltios de electrones recÃ­procos por metro cÃºbico');
  AddSafe('C89', 'Henry RecÃ­proco');
  AddSafe('C9', 'grupo de bobina');
  AddSafe('C90', 'Joule recÃ­proco por metro cÃºbico');
  AddSafe('C91', 'kelvin recÃ­proco o kelvin al poder menos uno');
  AddSafe('C92', 'medidor recÃ­proco');
  AddSafe('C93', 'metro cuadrado recÃ­proco');
  AddSafe('C94', 'minuto recÃ­proco');
  AddSafe('C95', 'mole recÃ­proco');
  AddSafe('C96', 'Pascal recÃ­proco o pascal a la potencia menos uno.');
  AddSafe('C97', 'segundo recÃ­proco');
  AddSafe('C98', 'segundo recÃ­proco por metro cÃºbico');
  AddSafe('C99', 'segundo recÃ­proco por metro cuadrado');
  AddSafe('CA', 'Caja');
  AddSafe('CCT', 'Capacidad de carga en toneladas mÃ©tricas.');
  AddSafe('CDL', 'candela');
  AddSafe('CEL', 'grado Celsius');
  AddSafe('CEN', 'cien');
  AddSafe('CG', 'tarjeta');
  AddSafe('CGM', 'centigramo');
  AddSafe('CH', 'envase');
  AddSafe('CJ', 'cono');
  AddSafe('CK', 'conector');
  AddSafe('CKG', 'Coulomb por kilogramo');
  AddSafe('CL', 'bobina');
  AddSafe('CLF', 'cientos de licencia');
  AddSafe('CLT', 'centilitro');
  AddSafe('CMK', 'centÃ­metro cuadrado');
  AddSafe('CMQ', 'centÃ­metro cÃºbico');
  AddSafe('CMT', 'centÃ­metro');
  AddSafe('CNP', 'paquete de cien');
  AddSafe('CNT', 'Cental (Reino Unido)');
  AddSafe('CO', 'garrafÃ³n');
  AddSafe('COU', 'culombio');
  AddSafe('CQ', 'cartucho');
  AddSafe('CR', 'caja');
  AddSafe('CS', 'caso');
  AddSafe('CT', 'caja de cartÃ³n');
  AddSafe('CTM', 'quilate mÃ©trico');
  AddSafe('CU', 'vaso');
  AddSafe('CUR', 'curie');
  AddSafe('CV', 'cubrir');
  AddSafe('CWA', 'cien libras (quintales) / cien pesos (US)');
  AddSafe('CWI', 'cien pesos (Reino Unido)');
  AddSafe('CY', 'cilindro');
  AddSafe('CZ', 'combo');
  AddSafe('D1', 'segundo recÃ­proco por esteradiano');
  AddSafe('D10', 'siemens por metro');
  AddSafe('D12', 'siemens metro cuadrado por mol');
  AddSafe('D13', 'sievert');
  AddSafe('D14', 'mil yardas lineales');
  AddSafe('D15', 'sone');
  AddSafe('D16', 'centÃ­metro cuadrado por ergio');
  AddSafe('D17', 'centÃ­metro cuadrado por erg esterlina');
  AddSafe('D18', 'metro kelvin');
  AddSafe('D19', 'kelvin metro cuadrado por vatio');
  AddSafe('D2', 'segundo recÃ­proco por metros cuadrados esteradianos');
  AddSafe('D20', 'metro cuadrado por julio');
  AddSafe('D21', 'metro cuadrado por kilogramo');
  AddSafe('D22', 'metro cuadrado por mol');
  AddSafe('D23', 'pluma gramo (proteÃ­na)');
  AddSafe('D24', 'metro cuadrado por esterilizador');
  AddSafe('D25', 'metro cuadrado por julios esteradianos');
  AddSafe('D26', 'metro cuadrado por voltio segundo');
  AddSafe('D27', 'esteradiano');
  AddSafe('D28', 'sifÃ³n');
  AddSafe('D29', 'terahercios');
  AddSafe('D30', 'terajulio');
  AddSafe('D31', 'teravatio');
  AddSafe('D32', 'hora de teravatio');
  AddSafe('D33', 'tesla');
  AddSafe('D34', 'Texas');
  AddSafe('D35', 'calorÃ­a termoquÃ­mica');
  AddSafe('D37', 'calorÃ­a termoquÃ­mica por gramo kelvin');
  AddSafe('D38', 'calorÃ­as termoquÃ­micas por segundo centÃ­metro kelvin');
  AddSafe('D39', 'calorÃ­as termoquÃ­micas por segundo centÃ­metro cuadrado kelvin');
  AddSafe('D40', 'mil litros');
  AddSafe('D41', 'tonelada por metro cÃºbico');
  AddSafe('D42', 'aÃ±o tropical');
  AddSafe('D43', 'unidad de masa atÃ³mica unificada');
  AddSafe('D44', 'var');
  AddSafe('D45', 'voltios al cuadrado por kelvin al cuadrado');
  AddSafe('D46', 'voltio â amperio');
  AddSafe('D47', 'voltio por centÃ­metro');
  AddSafe('D48', 'voltio por kelvin');
  AddSafe('D49', 'milivoltios por kelvin');
  AddSafe('D5', 'kilogramo por centÃ­metro cuadrado');
  AddSafe('D50', 'voltios por metro');
end;

class procedure TDianUnits.PopulatePart7;
begin
  AddSafe('D51', 'voltios por milÃ­metro');
  AddSafe('D52', 'vatios por kelvin');
  AddSafe('D53', 'vatios por metro kelvin');
  AddSafe('D54', 'vatios por metro cuadrado');
  AddSafe('D55', 'vatios por metro cuadrado kelvin');
  AddSafe('D56', 'vatios por metro cuadrado de kelvin a la cuarta potencia');
  AddSafe('D57', 'vatios por steradian');
  AddSafe('D58', 'vatios por metro cuadrado esterlino');
  AddSafe('D59', 'weber por metro');
  AddSafe('D6', 'rÃ¶ntgen por segundo');
  AddSafe('D60', 'weber por milÃ­metro');
  AddSafe('D61', 'minuto');
  AddSafe('D62', 'segundo');
  AddSafe('D63', 'libro');
  AddSafe('D64', 'bloquear');
  AddSafe('D65', 'redondo');
  AddSafe('D66', 'casete');
  AddSafe('D67', 'dÃ³lar por hora');
  AddSafe('D69', 'pulgada a la cuarta potencia');
  AddSafe('D7', 'Sandwich');
  AddSafe('D70', 'Tabla Internacional (IT) calorÃ­a');
  AddSafe('D71', 'Tabla Internacional (IT) calorÃ­as por segundo centÃ­metro kelvin');
  AddSafe('D72', 'Tabla Internacional (IT) calorÃ­as por segundo centÃ­metro cuadrado kelvin');
  AddSafe('D73', 'joule metro cuadrado');
  AddSafe('D74', 'kilogramo por mol');
  AddSafe('D75', 'Tabla Internacional (IT) calorÃ­as por gramo');
  AddSafe('D76', 'Tabla Internacional (IT) calorÃ­as por gramo kelvin');
  AddSafe('D77', 'megacoulomb');
  AddSafe('D79', 'haz');
  AddSafe('D8', 'puntaje de drenaje');
  AddSafe('D80', 'microwatt');
  AddSafe('D81', 'microtesla');
  AddSafe('D82', 'microvoltio');
  AddSafe('D83', 'medidor de millinewton');
  AddSafe('D85', 'microwatt por metro cuadrado');
  AddSafe('D86', 'Millicoulomb');
  AddSafe('D87', 'milimol por kilogramo');
  AddSafe('D88', 'millicoulomb por metro cÃºbico');
  AddSafe('D89', 'millicoulomb por metro cuadrado');
  AddSafe('D9', 'dina por centÃ­metro cuadrado');
  AddSafe('D90', 'metro cÃºbico (neto)');
  AddSafe('D91', 'movimiento rÃ¡pido del ojo');
  AddSafe('D92', 'banda');
  AddSafe('D93', 'segundo por metro cÃºbico');
  AddSafe('D94', 'segundo por metro cÃºbico radianes');
  AddSafe('D95', 'julios por gramo');
  AddSafe('D96', 'libra bruta');
  AddSafe('D97', 'carga de palet / unidad');
  AddSafe('D98', 'libra de masa');
  AddSafe('D99', 'manga');
  AddSafe('DAA', 'despreciar');
  AddSafe('DAD', 'diez dias');
  AddSafe('DAY', 'dÃ­a');
  AddSafe('DB', 'libra seca');
  AddSafe('DC', 'disco');
  AddSafe('DD', 'la licenciatura');
  AddSafe('DE', 'acuerdo');
  AddSafe('DEC', 'dÃ©cada');
  AddSafe('DG', 'decigramo');
  AddSafe('DI', 'dispensador');
  AddSafe('DJ', 'decagramo');
  AddSafe('DLT', 'decilitro');
  AddSafe('DMK', 'nformaci cuadrado');
  AddSafe('DMQ', 'decÃ­metro cÃºbico');
  AddSafe('DMT', 'decÃ­metro');
  AddSafe('DN', 'medidor de decinewton');
  AddSafe('DPC', 'docena pieza');
  AddSafe('DPR', 'docena par');
  AddSafe('DPT', 'tonelaje de desplazamiento');
  AddSafe('DQ', 'registro de datos');
  AddSafe('DR', 'tambor');
  AddSafe('DRA', 'dram (US)');
  AddSafe('DRI', 'dram (Reino Unido)');
  AddSafe('DRL', 'docena rollo');
  AddSafe('DRM', 'dracma (Reino Unido)');
  AddSafe('DS', 'monitor');
  AddSafe('DT', 'tonelada seca');
  AddSafe('DTN', 'Decitonne');
  AddSafe('DU', 'dina');
  AddSafe('DWT', 'pennyweight');
  AddSafe('DX', 'dina por centÃ­metro');
  AddSafe('DY', 'libro de directorio');
end;

class procedure TDianUnits.PopulatePart8;
begin
  AddSafe('DZN', 'docena');
  AddSafe('DZP', 'paquete de doce');
  AddSafe('E2', 'cinturÃ³n');
  AddSafe('E3', 'remolque');
  AddSafe('E4', 'kilogramo bruto');
  AddSafe('E5', 'tonelada mÃ©trica larga');
  AddSafe('EA', 'cada');
  AddSafe('EB', 'casilla de correo electrÃ³nico');
  AddSafe('CE', 'cada uno por mes');
  AddSafe('EP', 'paquete de once');
  AddSafe('EQ', 'galÃ³n equivalente');
  AddSafe('EV', 'sobre');
  AddSafe('F1', 'mil pies cÃºbicos por dÃ­a');
  AddSafe('F9', 'Fibra por centÃ­metro cÃºbico de aire');
  AddSafe('FAH', 'grado Fahrenheit');
  AddSafe('FAR', 'faradio');
  AddSafe('FB', 'campo');
  AddSafe('FC', 'mil pies cÃºbicos');
  AddSafe('FD', 'millÃ³n de partÃ­culas por pie cÃºbico');
  AddSafe('FE', 'pie de pista');
  AddSafe('FF', 'cien metros cÃºbicos');
  AddSafe('FG', 'parche transdÃ©rmico');
  AddSafe('FH', 'micromol');
  AddSafe('FL', 'tonelada en escamas');
  AddSafe('FM', 'millones de pies cÃºbicos');
  AddSafe('FOT', 'pie');
  AddSafe('FP', 'libra por pie cuadrado');
  AddSafe('FR', 'pie por minuto');
  AddSafe('FS', 'pie por segundo');
  AddSafe('FTK', 'pie cuadrado');
  AddSafe('FTQ', 'pie cubico');
  AddSafe('G2', 'US galones por minuto');
  AddSafe('G3', 'Galon imperial por minuto');
  AddSafe('G7', 'hoja de microficha');
  AddSafe('GB', 'galÃ³n (US) por dÃ­a');
  AddSafe('GBQ', 'gigabecquerel');
  AddSafe('GC', 'gramo por 100 gramo');
  AddSafe('GD', 'barril bruto');
  AddSafe('GE', 'libra por galÃ³n (US)');
  AddSafe('GF', 'gramo por metro (gramo por 100 centÃ­metros)');
  AddSafe('GFI', 'gramo de isÃ³topo fisionable');
  AddSafe('GGR', 'gramo');
  AddSafe('GH', 'medio galÃ³n (EE. UU.)');
  AddSafe('GIA', 'branquias');
  AddSafe('GII', 'Gill (Reino Unido)');
  AddSafe('GJ', 'gramo por mililitro');
  AddSafe('G K', 'gramo por kilogramo');
  AddSafe('GL', 'gramo por litro');
  AddSafe('GLD', 'galÃ³n seco (EE. UU.)');
  AddSafe('GLI', 'galÃ³n (Reino Unido)');
  AddSafe('GLL', 'galÃ³n');
  AddSafe('GM', 'gramo por metro cuadrado');
  AddSafe('GN', 'galÃ³n bruto');
  AddSafe('GO', 'miligramos por metro cuadrado');
  AddSafe('GP', 'miligramo por metro cÃºbico');
  AddSafe('GQ', 'microgramos por metro cÃºbico');
  AddSafe('GRM', 'gramo');
  AddSafe('GRN', 'grano');
  AddSafe('GRO', 'bruto');
  AddSafe('GRT', 'tonelada de registro bruto');
  AddSafe('GT', 'tonelada bruta');
  AddSafe('GV', 'gigajoule');
  AddSafe('GW', 'galÃ³n por mil pies cÃºbicos');
  AddSafe('GWH', 'hora de gigavatios');
  AddSafe('GY', 'patio bruto');
  AddSafe('GZ', 'sistema de mediciÃ³n');
  AddSafe('H1', 'media pÃ¡gina â electrÃ³nica');
  AddSafe('H2', 'medio litro');
  AddSafe('HA', 'madeja');
  AddSafe('HAR', 'hectÃ¡rea');
  AddSafe('HBA', 'hectobar');
  AddSafe('HBX', 'cien cajas');
  AddSafe('HC', 'cien cuentas');
  AddSafe('HD', 'media docena');
  AddSafe('ÃL', 'centÃ©sima de quilate');
  AddSafe('HF', 'cien pies');
  AddSafe('HGM', 'hectogramo');
  AddSafe('HH', 'cien pies cÃºbicos');
  AddSafe('HI', 'cien hojas');
  AddSafe('HIU', 'cien unidades internacionales');
  AddSafe('HJ', 'caballo mÃ©trico');
end;

class procedure TDianUnits.PopulatePart9;
begin
  AddSafe('HK', 'cien kilogramos');
  AddSafe('HL', 'cien pies (lineales)');
  AddSafe('HLT', 'hectolitro');
  AddSafe('HM', 'milla por hora');
  AddSafe('HMQ', 'millones de metros cÃºbicos');
  AddSafe('HMT', 'hectÃ³metro');
  AddSafe('HN', 'milÃ­metro convencional de mercurio');
  AddSafe('HO', 'cien onzas troy');
  AddSafe('HP', 'milÃ­metro convencional de agua');
  AddSafe('HPA', 'hectolitro de alcohol puro');
  AddSafe('HS', 'cien pies cuadrados');
  AddSafe('HT', 'media hora');
  AddSafe('HTZ', 'hertz');
  AddSafe('HUR', 'hora');
  AddSafe('HY', 'cien yardas');
  AddSafe('IA', 'pulgada libra');
  AddSafe('IC', 'contar por pulgada');
  AddSafe('IE', 'persona');
  AddSafe('IF', 'pulgadas de agua');
  AddSafe('II', 'columna pulgada');
  AddSafe('IL', 'pulgada por minuto');
  AddSafe('IM', 'impresiÃ³n');
  AddSafe('INH', 'pulgada');
  AddSafe('INK', 'pulgada cuadrada');
  AddSafe('INQ', 'pulgada en cubos');
  AddSafe('IP', 'pÃ³liza de seguros');
  AddSafe('IT', 'conteo por centÃ­metro');
  AddSafe('IU', 'pulgada por segundo (velocidad lineal)');
  AddSafe('IV', 'pulgada por segundo al cuadrado (aceleraciÃ³n)');
  AddSafe('J2', 'julios por kilogramo');
  AddSafe('JB', 'jumbo');
  AddSafe('JE', 'joule por kelvin');
  AddSafe('JG', 'jarra');
  AddSafe('JK', 'megajulio por kilogramo');
  AddSafe('JM', 'megajulio por metro cÃºbico');
  AddSafe('JO', 'articulaciÃ³n');
  AddSafe('JOU', 'joule');
  AddSafe('JR', 'tarro');
  AddSafe('K1', 'demanda de kilovatios');
  AddSafe('K2', 'kilovoltios amperios reactivos de demanda');
  AddSafe('K3', 'kilovoltio amperio hora reactiva');
  AddSafe('K5', 'amperios kilovoltios (reactivos)');
  AddSafe('K6', 'kilolitro');
  AddSafe('KA', 'pastel');
  AddSafe('KB', 'kilocharacter');
  AddSafe('KBA', 'kilobar');
  AddSafe('KD', 'kilogramo decimal');
  AddSafe('KEL', 'kelvin');
  AddSafe('KF', 'kilopacket');
  AddSafe('KG', 'barrilete');
  AddSafe('KGM', 'kilogramo');
  AddSafe('KGS', 'kilogramo por segundo');
  AddSafe('KHZ', 'kilohercio');
  AddSafe('KI', 'Kilogramo por milÃ­metro de ancho');
  AddSafe('KJ', 'kilosegmento');
  AddSafe('KJO', 'kilojoule');
  AddSafe('KL', 'kilogramo por metro');
  AddSafe('KMH', 'kilÃ³metro por hora');
  AddSafe('KMK', 'kilometro cuadrado');
  AddSafe('KMQ', 'kilogramo por metro cÃºbico');
  AddSafe('KNI', 'kilogramo de nitrÃ³geno');
  AddSafe('KNS', 'kilogramo de sustancia nombrada');
  AddSafe('KNT', 'nudo');
  AddSafe('KO', 'Milliequivalencia de potasa cÃ¡ustica por gramo de producto.');
  AddSafe('KPA', 'kilopascal');
  AddSafe('KPH', 'kilogramo de hidrÃ³xido de potasio (potasa cÃ¡ustica)');
  AddSafe('KPO', 'kilogramo de Ã³xido de potasio');
  AddSafe('KPP', 'kilogramo de pentÃ³xido de fÃ³sforo (anhÃ­drido fosfÃ³rico)');
  AddSafe('KR', 'KilorÃÂ¶ntgen');
  AddSafe('KS', 'mil libras por pulgada cuadrada');
  AddSafe('KSD', 'kilogramo de sustancia 90% seca');
  AddSafe('KSH', 'kilogramo de hidrÃ³xido de sodio (soda cÃ¡ustica)');
  AddSafe('KT', 'equipo');
  AddSafe('KTM', 'kilÃ³metro');
  AddSafe('KTN', 'kilotonne');
  AddSafe('KUR', 'kilogramo de uranio');
  AddSafe('KVA', 'kilovoltio â ampere');
  AddSafe('KVR', 'kilovar');
  AddSafe('KVT', 'kilovoltio');
  AddSafe('KW', 'kilogramos por milÃ­metro');
end;

class procedure TDianUnits.PopulatePart10;
begin
  AddSafe('KWH', 'kilovatios hora');
  AddSafe('KWT', 'kilovatio');
  AddSafe('KX', 'mililitro por kilogramo');
  AddSafe('L2', 'litro por minuto');
  AddSafe('LA', 'libra por pulgada cÃºbica');
  AddSafe('LBR', 'libra');
  AddSafe('LBT', 'libra troy');
  AddSafe('LC', 'centÃ­metro lineal');
  AddSafe('LD', 'litro por dÃ­a');
  AddSafe('LE', 'lite');
  AddSafe('LEF', 'hoja');
  AddSafe('LF', 'pie lineal');
  AddSafe('LH', 'hora de trabajo');
  AddSafe('LI', 'pulgada lineal');
  AddSafe('LJ', 'spray grande');
  AddSafe('LK', 'enlazar');
  AddSafe('LM', 'metro lineal');
  AddSafe('LN', 'longitud');
  AddSafe('LO', 'mucho');
  AddSafe('LP', 'libra liquida');
  AddSafe('LPA', 'litro de alcohol puro');
  AddSafe('LR', 'capa');
  AddSafe('LS', 'Suma global');
  AddSafe('LTN', 'ton (Reino Unido) o longton (EE. UU.)');
  AddSafe('LTR', 'litro');
  AddSafe('LUM', 'lumen');
  AddSafe('LUX', 'lux');
  AddSafe('LX', 'yarda lineal por libra');
  AddSafe('LY', 'yarda lineal');
  AddSafe('M0', 'cinta magnÃ©tica');
  AddSafe('M1', 'miligramos por litro');
  AddSafe('M4', 'valor monetario');
  AddSafe('M5', 'microcurie');
  AddSafe('M7', 'micropulgada');
  AddSafe('M9', 'millones de Btu por 1000 pies cÃºbicos');
  AddSafe('MA', 'mÃ¡quina por unidad');
  AddSafe('MAL', 'mega litro');
  AddSafe('MAM', 'megametro');
  AddSafe('MAW', 'megavatio');
  AddSafe('MBE', 'mil equivalentes de ladrillo estÃ¡ndar');
  AddSafe('MBF', 'mil pies de tabla');
  AddSafe('MBR', 'milibar');
  AddSafe('MC', 'microgramo');
  AddSafe('MCU', 'milicurie');
  AddSafe('MD', 'aire seco tonelada mÃ©trica');
  AddSafe('MF', 'miligramo por pie cuadrado por lado');
  AddSafe('MG', 'miligramo');
  AddSafe('MHZ', 'megahercio');
  AddSafe('MIK', 'milla cuadrada');
  AddSafe('MIL', 'mil');
  AddSafe('MIN', 'minuto');
  AddSafe('MIO', 'millÃ³n');
  AddSafe('MIU', 'millones de unidades internacionales');
  AddSafe('MK', 'miligramo por pulgada cuadrada');
  AddSafe('MLD', 'mil millones');
  AddSafe('MLT', 'mililitro');
  AddSafe('MMK', 'milÃ­metro cuadrado');
  AddSafe('MMQ', 'milÃ­metro cÃºbico');
  AddSafe('MMT', 'milÃ­metro');
  AddSafe('LUN', 'mes');
  AddSafe('MPA', 'megapascal');
  AddSafe('MQ', 'mil metros');
  AddSafe('MQH', 'metro cÃºbico por hora');
  AddSafe('MQS', 'metro cÃºbico por segundo');
  AddSafe('MSK', 'metro por segundo al cuadrado');
  AddSafe('MT', 'estera');
  AddSafe('MTK', 'metro cuadrado');
  AddSafe('MTQ', 'Metro cÃºbico');
  AddSafe('MTR', 'metro');
  AddSafe('MTS', 'metro por segundo');
  AddSafe('MV', 'numero de mults');
  AddSafe('MVA', 'megavolt â ampere');
  AddSafe('MWH', 'megavatios hora (1000 kW.h)');
  AddSafe('N1', 'calorÃ­as de la pluma');
  AddSafe('N2', 'nÃºmero de lÃ­neas');
  AddSafe('N3', 'punto de impresiÃ³n');
  AddSafe('NA', 'miligramo por kilogramo');
  AddSafe('NAR', 'nÃºmero de artÃ­culos');
  AddSafe('NB', 'barcaza');
  AddSafe('NBB', 'nÃºmero de bobinas');
  AddSafe('NC', 'coche');
  AddSafe('NCL', 'nÃºmero de celdas');
  AddSafe('ND', 'barril neto');
  AddSafe('NE', 'litro neto');
  AddSafe('NEW', 'newton');
  AddSafe('NF', 'mensaje');
  AddSafe('NG', 'galÃ³n neto (nosotros)');
  AddSafe('NH', 'hora del mensaje');
  AddSafe('NI', 'galÃ³n imperial neto');
  AddSafe('NIU', 'nÃºmero de unidades internacionales');
  AddSafe('NJ', 'nÃºmero de pantallas');
  AddSafe('NL', 'carga');
  AddSafe('MNI', 'milla nautica');
  AddSafe('NMP', 'nÃºmero de paquetes');
  AddSafe('NN', 'entrenar');
  AddSafe('NPL', 'nÃºmero de parcelas');
  AddSafe('NPR', 'numero de pares');
  AddSafe('TNP', 'numero de partes');
  AddSafe('NQ', 'mho');
  AddSafe('NR', 'micromho');
  AddSafe('NRL', 'nÃºmero de rollos');
  AddSafe('NT', 'tonelada neta');
  AddSafe('NTT', 'registro neto de toneladas');
  AddSafe('NU', 'medidor de newton');
  AddSafe('NV', 'vehÃ­culo');
  AddSafe('NX', 'parte por mil');
  AddSafe('NY', 'libra por aire seco tonelada mÃ©trica');
  AddSafe('OA', 'panel');
  AddSafe('OHM', 'ohm');
  AddSafe('EN', 'onza por yarda cuadrada');
  AddSafe('ONZ', 'onza');
  AddSafe('OP', 'Dos paquetes');
  AddSafe('OT', 'hora extra');
  AddSafe('ONZ', 'onza av');
  AddSafe('OZA', 'onza lÃ­quida (US)');
  AddSafe('OZI', 'onza lÃ­quida (Reino Unido)');
  AddSafe('P0', 'pagina â electronica');
  AddSafe('P1', 'por ciento');
  AddSafe('P2', 'libra por pie');
  AddSafe('P3', 'paquete de tres');
  AddSafe('P4', 'paquete de cuatro');
  AddSafe('P5', 'paquete de cinco');
  AddSafe('P6', 'paquete de seis');
  AddSafe('P7', 'paquete de siete');
  AddSafe('P8', 'paquete de ocho');
  AddSafe('P9', 'paquete de nueve');
  AddSafe('PA', 'paquete');
  AddSafe('PAL', 'pascal');
  AddSafe('PB', 'par de pulgadas');
  AddSafe('PD', 'almohadilla');
  AddSafe('PE', 'equivalente en libras');
  AddSafe('PF', 'palet (ascensor)');
  AddSafe('PG', 'plato');
  AddSafe('PGL', 'galÃ³n de prueba');
  AddSafe('Pi', 'tono');
  AddSafe('PK', 'paquete');
  AddSafe('PL', 'cubo');
  AddSafe('PM', 'porcentaje de libra');
  AddSafe('PN', 'libra neta');
  AddSafe('PO', 'libra por pulgada de longitud');
  AddSafe('PQ', 'pÃ¡gina por pulgada');
  AddSafe('PR', 'par');
  AddSafe('PD', 'fuerza de libra por pulgada cuadrada');
  AddSafe('PT', 'pinta');
  AddSafe('PTD', 'pinta seca');
  AddSafe('PTI', 'pinta (Reino Unido)');
  AddSafe('PTL', 'pinta liquida (US)');
  AddSafe('PU', 'bandeja / paquete de bandeja');
  AddSafe('PV', 'media pinta (US)');
  AddSafe('PW', 'libra por pulgada de ancho');
  AddSafe('PY', 'Peck Dry (US)');
  AddSafe('PZ', 'Peck Dry (Reino Unido)');
  AddSafe('Q3', 'comida');
  AddSafe('QA', 'pÃ¡gina â facsÃ­mil');
  AddSafe('QAN', 'cuarto (de un aÃ±o)');
  AddSafe('QB', 'pÃ¡gina â copia impresa');
  AddSafe('QD', 'cuarto de docena');
  AddSafe('QH', 'un cuarto de hora');
  AddSafe('QK', 'cuarto de kilogramo');
  AddSafe('QR', 'mano de papel');
  AddSafe('QT', 'cuarto de galÃ³n (US)');
  AddSafe('QTD', 'cuarto seco (EE. UU.)');
  AddSafe('QTI', 'cuarto de galÃ³n (Reino Unido)');
  AddSafe('QTL', 'cuarto lÃ­quido (US)');
  AddSafe('QTR', 'cuarto (UK)');
  AddSafe('R1', 'pica');
  AddSafe('R4', 'calorÃ­a');
  AddSafe('R9', 'mil metros cÃºbicos');
  AddSafe('RA', 'estante');
  AddSafe('RD', 'barra');
  AddSafe('RG', 'anillo');
  AddSafe('RH', 'hora de funcionamiento o de funcionamiento');
  AddSafe('RK', 'medida mÃ©trica rollo');
  AddSafe('RL', 'carrete');
  AddSafe('RM', 'resma');
  AddSafe('RN', 'medida mÃ©trica de resma');
  AddSafe('RO', 'rodar');
  AddSafe('RP', 'libra por resma');
  AddSafe('RPM', 'revoluciones por minuto');
  AddSafe('RPS', 'revoluciones por segundo');
  AddSafe('RS', 'Reiniciar');
  AddSafe('RT', 'ingreso tonelada milla');
  AddSafe('RU', 'correr');
  AddSafe('S3', 'pie cuadrado por segundo');
  AddSafe('S4', 'metro cuadrado por segundo');
  AddSafe('S5', 'sesenta cuartos de pulgada');
  AddSafe('S6', 'sesiÃ³n');
  AddSafe('S7', 'unidad de almacenamiento');
  AddSafe('S8', 'unidad de publicidad estÃ¡ndar');
  AddSafe('SA', 'saco');
  AddSafe('SAN', 'medio aÃ±o (6 meses)');
  AddSafe('OCS', 'PuntuaciÃ³n');
  AddSafe('SCR', 'escrÃºpulo');
  AddSafe('SD', 'libra solida');
  AddSafe('SE', 'secciÃ³n');
  AddSafe('SEC', 'segundo');
  AddSafe('SET', 'conjunto');
  AddSafe('SG', 'segmento');
  AddSafe('SHT', 'tonelada de envÃ­o');
  AddSafe('SIE', 'siemens');
  AddSafe('SK', 'camiÃ³n cisterna dividido');
  AddSafe('SL', 'hoja de deslizamiento');
  AddSafe('SMI', 'milla (milla estatutaria)');
  AddSafe('SN', 'varilla cuadrada');
  AddSafe('SO', 'carrete');
  AddSafe('SP', 'paquete de estante');
  AddSafe('SQ', 'cuadrado');
  AddSafe('SR', 'tira');
  AddSafe('SS', 'hoja mÃ©trica medida');
  AddSafe('SST', 'corto estÃ¡ndar (7200 partidos)');
  AddSafe('ST', 'hoja');
  AddSafe('ITS', 'piedra (Reino Unido)');
  AddSafe('STN', 'tonelada (US) o tonelada corta (UK / US)');
  AddSafe('SV', 'patinar');
  AddSafe('SO', 'madeja');
  AddSafe('SX', 'envÃ­o');
  AddSafe('T0', 'LÃ­nea de telecomunicaciones en servicio.');
  AddSafe('T1', 'mil libras brutas');
  AddSafe('T3', 'mil piezas');
  AddSafe('T4', 'bolsa de mil');
  AddSafe('T5', 'caja de mil');
  AddSafe('T6', 'mil galones (US)');
  AddSafe('T7', 'mil impresiones');
  AddSafe('T8', 'mil pulgadas lineales');
  AddSafe('TA', 'dÃ©cimo pie cÃºbico');
  AddSafe('TAH', 'Kiloampere hora (mil amperios hora)');
  AddSafe('TC', 'camion');
  AddSafe('TD', 'termia');
  AddSafe('TE', 'totalizador');
  AddSafe('TF', 'diez metros cuadrados');
  AddSafe('TI', 'mil pulgadas cuadradas');
  AddSafe('TJ', 'mil centÃ­metros cuadrados');
  AddSafe('TK', 'tanque, rectangular');
  AddSafe('TL', 'mil pies (lineales)');
  AddSafe('TN', 'estaÃ±o');
  AddSafe('TNE', 'tonelada (tonelada mÃ©trica)');
  AddSafe('TP', 'paquete de diez');
  AddSafe('TPR', 'diez pares');
  AddSafe('TQ', 'mil pies');
  AddSafe('TQD', 'mil metros cÃºbicos por dÃ­a');
  AddSafe('TR', 'diez pies cuadrados');
  AddSafe('TRL', 'trillÃ³n (EUR)');
  AddSafe('TS', 'mil pies cuadrados');
  AddSafe('TSD', 'tonelada de sustancia 90% seca');
  AddSafe('TSH', 'tonelada de vapor por hora');
  AddSafe('TT', 'mil metros lineales');
  AddSafe('TU', 'tubo');
  AddSafe('TV', 'mil kilogramos');
  AddSafe('TW', 'mil hojas');
  AddSafe('TY', 'tanque, cilÃ­ndrico');
  AddSafe('U1', 'tratamiento');
  AddSafe('U2', 'tableta');
  AddSafe('UA', 'torr');
  AddSafe('UB', 'LÃ­nea de telecomunicaciones en servicio promedio.');
  AddSafe('UC', 'puerto de telecomunicaciones');
  AddSafe('UD', 'dÃ©cimo minuto');
  AddSafe('UE', 'dÃ©cima hora');
  AddSafe('UF', 'uso por lÃ­nea de telecomunicaciÃ³n promedio');
  AddSafe('UH', 'diez mil yardas');
  AddSafe('UM', 'millones de unidades');
  AddSafe('VA', 'voltio amperio por kilogramo');
  AddSafe('VI', 'frasco');
  AddSafe('VLT', 'voltio');
  AddSafe('VQ', 'abultar');
  AddSafe('VS', 'visitar');
  AddSafe('W2', 'kilo mojado');
  AddSafe('W4', 'dos semanas');
  AddSafe('WA', 'vatio por kilogramo');
  AddSafe('WB', 'libra mojada');
  AddSafe('WCD', 'cable');
  AddSafe('WE', 'tonelada mojada');
  AddSafe('WEB', 'weber');
  AddSafe('WEE', 'semana');
  AddSafe('WG', 'galon de vino');
  AddSafe('WH', 'rueda');
  AddSafe('WHR', 'vatios hora');
  AddSafe('WI', 'peso por pulgada cuadrada');
  AddSafe('WM', 'mes de trabajo');
  AddSafe('WR', 'envolver');
  AddSafe('WSD', 'estÃ¡ndar');
  AddSafe('WTT', 'vatio');
  AddSafe('WW', 'mililitro de agua');
  AddSafe('X1', 'cadena');
  AddSafe('YDK', 'yarda cuadrada');
  AddSafe('YDQ', 'Yarda cÃºbica');
  AddSafe('YL', 'cien yardas lineales');
  AddSafe('YRD', 'yarda');
  AddSafe('YT', 'diez yardas');
  AddSafe('Z1', 'van de elevaciÃ³n');
  AddSafe('Z2', 'pecho');
  AddSafe('Z3', 'barril');
  AddSafe('Z4', 'pipa');
  AddSafe('Z5', 'arrastrar');
  AddSafe('Z6', 'punto de conferencia');
  AddSafe('Z8', 'lÃ­nea de noticias de Ã¡gata');
  AddSafe('ZP', 'pÃ¡gina');
  AddSafe('ZZ', 'mutuamente definido');
end;

end.
