unit DianUnits;

interface

uses
  System.Generics.Collections,
  System.SysUtils;

type
  TDianUnits = class
  private
    class var FUnitMap: TDictionary<string, string>;
    class constructor Create;
    class destructor Destroy;
  public
    /// <summary>
    /// Obtiene el nombre de la unidad de medida DIAN para un código dado.
    /// Si el código no existe, retorna el mismo código.
    /// </summary>
    class function GetUnitName(const ACode: string): string;

    /// <summary>
    /// Verifica si existe un código de unidad de medida en el catálogo DIAN.
    /// </summary>
    class function Exists(const ACode: string): Boolean;
  end;

implementation

{ TDianUnits }

class constructor TDianUnits.Create;
begin
  FUnitMap := TDictionary<string, string>.Create;

  // === Carga de unidades de medida DIAN (Genericode v2.1) ===
  // Última actualización: 18-02-2019
  // Fuente: DIAN - Dirección de Impuestos y Aduanas Nacionales

  FUnitMap.Add('04', 'spray pequeño');
  FUnitMap.Add('05', 'levantar');
  FUnitMap.Add('08', 'Lote calor');
  FUnitMap.Add('10', 'grupo');
  FUnitMap.Add('11', 'equipar');
  FUnitMap.Add('13', 'ración');
  FUnitMap.Add('14', 'Disparo');
  FUnitMap.Add('15', 'palo');
  FUnitMap.Add('16', 'tambor de ciento quince kg');
  FUnitMap.Add('17', 'tambor de cien libras');
  FUnitMap.Add('18', 'tambor de cincuenta y cinco galones (US)');
  FUnitMap.Add('19', 'camión cisterna');
  FUnitMap.Add('20', 'contenedor de veinte pies');
  FUnitMap.Add('21', 'contenedor de cuarenta pies');
  FUnitMap.Add('22', 'decilitro por gramo');
  FUnitMap.Add('23', 'gramo por centímetro cúbico');
  FUnitMap.Add('24', 'libra teórica');
  FUnitMap.Add('25', 'gramo por centímetro cuadrado');
  FUnitMap.Add('26', 'tonelada real');
  FUnitMap.Add('27', 'tonelada teórica');
  FUnitMap.Add('28', 'kilogramo por metro cuadrado');
  FUnitMap.Add('29', 'libra por mil pies cuadrados');
  FUnitMap.Add('30', 'Día de potencia del caballo por tonelada métrica seca al aire.');
  FUnitMap.Add('31', 'coger peso');
  FUnitMap.Add('32', 'kilogramo por aire seco tonelada métrica');
  FUnitMap.Add('33', 'kilopascales metros cuadrados por gramo');
  FUnitMap.Add('34', 'kilopascales por milímetro');
  FUnitMap.Add('35', 'mililitros por centímetro cuadrado segundo');
  FUnitMap.Add('36', 'pies cúbicos por minuto por pie cuadrado');
  FUnitMap.Add('37', 'onza por pie cuadrado');
  FUnitMap.Add('38', 'onzas por pie cuadrado por 0,01 pulgadas');
  FUnitMap.Add('40', 'mililitro por segundo');
  FUnitMap.Add('41', 'mililitro por minuto');
  FUnitMap.Add('43', 'bolsa súper a granel');
  FUnitMap.Add('44', 'bolsa a granel de quinientos kg');
  FUnitMap.Add('45', 'bolsa a granel de trescientos kg');
  FUnitMap.Add('46', 'bolsa a granel de cincuenta libras');
  FUnitMap.Add('47', 'bolsa de cincuenta libras');
  FUnitMap.Add('48', 'carga de automóviles a granel');
  FUnitMap.Add('53', 'kilogramos teóricos');
  FUnitMap.Add('54', 'tonelada teórica');
  FUnitMap.Add('56', 'sitas');
  FUnitMap.Add('57', 'malla');
  FUnitMap.Add('58', 'kilogramo neto');
  FUnitMap.Add('59', 'parte por millón');
  FUnitMap.Add('60', 'porcentaje de peso');
  FUnitMap.Add('61', 'parte por billón (US)');
  FUnitMap.Add('62', 'porcentaje por 1000 horas');
  FUnitMap.Add('63', 'tasa de fracaso en el tiempo');
  FUnitMap.Add('64', 'libra por pulgada cuadrada, calibre');
  FUnitMap.Add('66', 'Oersted');
  FUnitMap.Add('69', 'prueba de escala específica');
  FUnitMap.Add('71', 'voltio amperio por libra');
  FUnitMap.Add('72', 'vatio por libra');
  FUnitMap.Add('73', 'amperio tum por centímetro');
  FUnitMap.Add('74', 'milipascal');
  FUnitMap.Add('76', 'gauss');
  FUnitMap.Add('77', 'mili pulgadas');
  FUnitMap.Add('78', 'kilogauss');
  FUnitMap.Add('80', 'libras por pulgada cuadrada absoluta');
  FUnitMap.Add('81', 'Enrique');
  FUnitMap.Add('84', 'kilopound por pulgada cuadrada');
  FUnitMap.Add('85', 'fuerza libra pie');
  FUnitMap.Add('87', 'libra por pie cúbico');
  FUnitMap.Add('89', 'equilibrio');
  FUnitMap.Add('90', 'Saybold segundo universal');
  FUnitMap.Add('91', 'alimenta');
  FUnitMap.Add('92', 'calorías por centímetro cúbico');
  FUnitMap.Add('93', 'calorías por gramo');
  FUnitMap.Add('94', 'unidad');
  FUnitMap.Add('95', 'veinte mil galones (US) de carros');
  FUnitMap.Add('96', 'diez mil galones (US) de carros');
  FUnitMap.Add('97', 'tambor de diez kg');
  FUnitMap.Add('98', 'tambor de quince kg');
  FUnitMap.Add('1ª', 'milla de coche');
  FUnitMap.Add('1B', 'recuento de coches');
  FUnitMap.Add('1C', 'recuento de locomotoras');
  FUnitMap.Add('1D', 'recuento de cabos');
  FUnitMap.Add('1E', 'carro vacio');
  FUnitMap.Add('1F', 'millas de tren');
  FUnitMap.Add('1G', 'uso de combustible galón (US)');
  FUnitMap.Add('1H', 'milla del caboose');
  FUnitMap.Add('1I', 'tipo de interés fijo');
  FUnitMap.Add('1J', 'tonelada milla');
  FUnitMap.Add('1K', 'milla locomotora');
  FUnitMap.Add('1L', 'recuento total de coches');
  FUnitMap.Add('1M', 'milla de coche total');
  FUnitMap.Add('1X', 'cuarto de milla');
  FUnitMap.Add('2ª', 'radianes por segundo');
  FUnitMap.Add('2B', 'radianes por segundo al cuadrado');
  FUnitMap.Add('2C', 'Röntgen');
  FUnitMap.Add('2I', 'Unidad térmica británica por hora.');
  FUnitMap.Add('2J', 'centímetro cúbico por segundo');
  FUnitMap.Add('2K', 'pie cúbico por hora');
  FUnitMap.Add('2L', 'pie cúbico por minuto');
  FUnitMap.Add('2M', 'centímetro por segundo');
  FUnitMap.Add('2N', 'decibel');
  FUnitMap.Add('2P', 'kilobyte');
  FUnitMap.Add('2Q', 'kilobecquerel');
  FUnitMap.Add('2R', 'kilocurie');
  FUnitMap.Add('2U', 'megagramo');
  FUnitMap.Add('2V', 'megagramo por hora');
  FUnitMap.Add('2W', 'compartimiento');
  FUnitMap.Add('2X', 'metro por minuto');
  FUnitMap.Add('2Y', 'milliröntgen');
  FUnitMap.Add('2Z', 'milivoltios');
  FUnitMap.Add('3B', 'megajulio');
  FUnitMap.Add('3C', 'manmonth');
  FUnitMap.Add('3E', 'libra por libra de producto');
  FUnitMap.Add('3G', 'libra por pieza de producto');
  FUnitMap.Add('3H', 'kilogramo por kilogramo de producto');
  FUnitMap.Add('3I', 'kilogramo por pieza de producto');
  FUnitMap.Add('4ª', 'bobina');
  FUnitMap.Add('4B', 'gorra');
  FUnitMap.Add('4C', 'centistokes');
  FUnitMap.Add('4E', 'paquete de veinte');
  FUnitMap.Add('4G', 'microlitro');
  FUnitMap.Add('4H', 'micrometro');
  FUnitMap.Add('4K', 'miliamperio');
  FUnitMap.Add('4L', 'megabyte');
  FUnitMap.Add('4M', 'miligramo por hora');
  FUnitMap.Add('4N', 'megabecquerel');
  FUnitMap.Add('4º', 'microfarad');
  FUnitMap.Add('4P', 'newton por metro');
  FUnitMap.Add('4Q', 'onza pulgada');
  FUnitMap.Add('4R', 'pie onza');
  FUnitMap.Add('4T', 'picofarad');
  FUnitMap.Add('4U', 'libra por hora');
  FUnitMap.Add('4W', 'tonelada (US) por hora');
  FUnitMap.Add('4X', 'kilolitro por hora');
  FUnitMap.Add('5ª', 'barril por minuto');
  FUnitMap.Add('5B', 'lote');
  FUnitMap.Add('5C', 'galón (US) por mil');
  FUnitMap.Add('5E', 'MMSCF / día');
  FUnitMap.Add('5F', 'libras por mil');
  FUnitMap.Add('5G', 'bomba');
  FUnitMap.Add('5H', 'escenario');
  FUnitMap.Add('5I', 'pie cúbico estándar');
  FUnitMap.Add('5J', 'potencia hidráulica de caballos');
  FUnitMap.Add('5K', 'contar por minuto');
  FUnitMap.Add('5P', 'nivel sismico');
  FUnitMap.Add('5Q', 'nfor sismica');
  FUnitMap.Add('A1', '15 calorías C');
  FUnitMap.Add('A10', 'amperio metro cuadrado por joule segundo');
  FUnitMap.Add('A11', 'Ã ¥ ngström');
  FUnitMap.Add('A12', 'unidad astronómica');
  FUnitMap.Add('A13', 'attojoule');
  FUnitMap.Add('A14', 'granero');
  FUnitMap.Add('A15', 'granero por electrón voltio');
  FUnitMap.Add('A16', 'granero por voltio de electrones esteradiano,');
  FUnitMap.Add('A17', 'granero por sterdian');
  FUnitMap.Add('A18', 'becquerel por kilogramo');
  FUnitMap.Add('A19', 'becquerel por metro cúbico');
  FUnitMap.Add('A2', 'amperio por centímetro');
  FUnitMap.Add('A20', 'Unidad térmica británica por segundo pie cuadrado grado Rankin');
  FUnitMap.Add('A21', 'Unidad térmica británica por libra grado Rankin');
  FUnitMap.Add('A22', 'Unidad térmica británica por segundo pie grado Rankin');
  FUnitMap.Add('A23', 'Unidad térmica británica por hora pie cuadrado grado Rankin');
  FUnitMap.Add('A24', 'candela por metro cuadrado');
  FUnitMap.Add('A25', 'cheval vapeur');
  FUnitMap.Add('A26', 'medidor de culombio');
  FUnitMap.Add('A27', 'medidor de culombio al cuadrado por voltio');
  FUnitMap.Add('A28', 'Coulomb por centímetro cúbico');
  FUnitMap.Add('A29', 'Coulomb por metro cúbico');
  FUnitMap.Add('A3', 'amperio por milímetro');
  FUnitMap.Add('A30', 'Coulomb por milímetro cúbico');
  FUnitMap.Add('A31', 'Coulomb por kilogramo segundo');
  FUnitMap.Add('A32', 'Coulomb por mol');
  FUnitMap.Add('A33', 'Coulomb por centímetro cuadrado');
  FUnitMap.Add('A34', 'Coulomb por metro cuadrado');
  FUnitMap.Add('A35', 'Coulomb por milímetro cuadrado');
  FUnitMap.Add('A36', 'centímetro cúbico por mol');
  FUnitMap.Add('A37', 'nformaci cúbico por mol');
  FUnitMap.Add('A38', 'metro cúbico por coulomb');
  FUnitMap.Add('A39', 'metro cúbico por kilogramo');
  FUnitMap.Add('A4', 'amperio por centímetro cuadrado');
  FUnitMap.Add('A40', 'metro cúbico por mol');
  FUnitMap.Add('A41', 'amperio por metro cuadrado');
  FUnitMap.Add('A42', 'curie por kilogramo');
  FUnitMap.Add('A43', 'tonelaje de peso muerto');
  FUnitMap.Add('A44', 'decalitro');
  FUnitMap.Add('A45', 'decámetro');
  FUnitMap.Add('A47', 'decitex');
  FUnitMap.Add('A48', 'grado Rankin');
  FUnitMap.Add('A49', 'negador');
  FUnitMap.Add('A5', 'amperio metro cuadrado');
  FUnitMap.Add('A50', 'dyn segundo por centímetro cúbico');
  FUnitMap.Add('A51', 'dina segundo por centímetro');
  FUnitMap.Add('A52', 'dina segundo por centímetro al quinto');
  FUnitMap.Add('A53', 'electronvolt');
  FUnitMap.Add('A54', 'electronvoltio por metro');
  FUnitMap.Add('A55', 'metro electronvolt cuadrado');
  FUnitMap.Add('A56', 'electronvoltio de metro cuadrado por kilogramo');
  FUnitMap.Add('A57', 'ergio');
  FUnitMap.Add('A58', 'erg por centímetro');
  FUnitMap.Add('A6', 'amperio por metro cuadrado kelvin al cuadrado');
  FUnitMap.Add('A60', 'erg por centímetro cúbico');
  FUnitMap.Add('A61', 'erg por gramo');
  FUnitMap.Add('A62', 'erg por gramo de segundo');
  FUnitMap.Add('A63', 'erg por segundo');
  FUnitMap.Add('A64', 'erg por segundo centímetro cuadrado');
  FUnitMap.Add('A65', 'erg por centímetro cuadrado segundo');
  FUnitMap.Add('A66', 'erg centímetro cuadrado');
  FUnitMap.Add('A67', 'ergímetro cuadrado por gramo');
  FUnitMap.Add('A68', 'exajulio');
  FUnitMap.Add('A69', 'faradio por metro');
  FUnitMap.Add('A7', 'amperio por milímetro cuadrado');
  FUnitMap.Add('A70', 'femtojoule');
  FUnitMap.Add('A71', 'femtometro');
  FUnitMap.Add('A73', 'pie por segundo al cuadrado');
  FUnitMap.Add('A74', 'pie-fuerza de la libra por segundo');
  FUnitMap.Add('A75', 'tonelada de carga');
  FUnitMap.Add('A76', 'galón');
  FUnitMap.Add('A77', 'Unidad de desplazamiento CGS gaussiana');
  FUnitMap.Add('A78', 'Unidad gaussiana CGS de corriente eléctrica.');
  FUnitMap.Add('A79', 'Unidad Gaussian CGS de carga eléctrica.');
  FUnitMap.Add('A8', 'amperio segundo');
  FUnitMap.Add('A80', 'Unidad Gaussian CGS de intensidad de campo eléctrico.');
  FUnitMap.Add('A81', 'Unidad Gaussian CGS de polarización eléctrica.');
  FUnitMap.Add('A82', 'Unidad Gaussian CGS de potencial eléctrico.');
  FUnitMap.Add('A83', 'Unidad Gaussiana CGS de magnetización.');
  FUnitMap.Add('A84', 'gigacoulomb por metro cúbico');
  FUnitMap.Add('A85', 'Gigaelectronvolt');
  FUnitMap.Add('A86', 'gigahercios');
  FUnitMap.Add('A87', 'gigaohm');
  FUnitMap.Add('A88', 'medidor de gigaohm');
  FUnitMap.Add('A89', 'gigapascal');
  FUnitMap.Add('A9', 'tarifa');
  FUnitMap.Add('A90', 'gigavatios');
  FUnitMap.Add('A91', 'gon');
  FUnitMap.Add('A93', 'gramo por metro cúbico');
  FUnitMap.Add('A94', 'gramo por mol');
  FUnitMap.Add('A95', 'gris');
  FUnitMap.Add('A96', 'gris por segundo');
  FUnitMap.Add('A97', 'hectopascal');
  FUnitMap.Add('A98', 'Henry por metro');
  FUnitMap.Add('AA', 'bola');
  FUnitMap.Add('AB', 'paquete a granel');
  FUnitMap.Add('ACR', 'acre');
  FUnitMap.Add('AD', 'byte');
  FUnitMap.Add('AE', 'amperio por metro');
  FUnitMap.Add('AH', 'minuto adicional');
  FUnitMap.Add('AI', 'minuto promedio por llamada');
  FUnitMap.Add('AJ', 'policía');
  FUnitMap.Add('AK', 'braza');
  FUnitMap.Add('AL', 'nfor de acceso');
  FUnitMap.Add('AM', 'ampolla');
  FUnitMap.Add('AMH', 'hora amperio');
  FUnitMap.Add('AMP', 'amperio');
  FUnitMap.Add('ANA', 'año');
  FUnitMap.Add('AP', 'solo libra de aluminio');
  FUnitMap.Add('APZ', 'onza troy o onza de boticarios');
  FUnitMap.Add('AQ', 'Unidad de factor antihemofílico (AHF)');
  FUnitMap.Add('AR', 'supositorio');
  FUnitMap.Add('SON', 'son');
  FUnitMap.Add('COMO', 'surtido');
  FUnitMap.Add('ASM', 'fuerza alcohólica en masa');
  FUnitMap.Add('ASU', 'fuerza alcohólica por volumen');
  FUnitMap.Add('ATM', 'ambiente estándar');
  FUnitMap.Add('ATT', 'ambiente técnico');
  FUnitMap.Add('AV', 'cápsula');
  FUnitMap.Add('AW', 'vial lleno de polvo');
  FUnitMap.Add('SÍ', 'montaje');
  FUnitMap.Add('AZ', 'Unidad térmica británica por libra');
  FUnitMap.Add('B0', 'Btu por pie cúbico');
  FUnitMap.Add('B1', 'barril (US) por día');
  FUnitMap.Add('B11', 'julios por kilogramo kelvin');
  FUnitMap.Add('B12', 'julios por metro');
  FUnitMap.Add('B13', 'julios por metro cuadrado');
  FUnitMap.Add('B14', 'julios por metro a la cuarta potencia');
  FUnitMap.Add('B15', 'julios por mol');
  FUnitMap.Add('B16', 'julios por mol kelvin');
  FUnitMap.Add('B18', 'joule segundo');
  FUnitMap.Add('B2', 'litera');
  FUnitMap.Add('B20', 'joule metro cuadrado por kilogramo');
  FUnitMap.Add('B21', 'kelvin por vatio');
  FUnitMap.Add('B22', 'Kiloampere');
  FUnitMap.Add('B23', 'kiloampere por metro cuadrado');
  FUnitMap.Add('B24', 'kiloampere por metro');
  FUnitMap.Add('B25', 'kilobecquerel por kilogramo');
  FUnitMap.Add('B26', 'kilocoulomb');
  FUnitMap.Add('B27', 'kilocoulomb por metro cúbico');
  FUnitMap.Add('B28', 'kilocoulomb por metro cuadrado');
  FUnitMap.Add('B29', 'kiloelectronvolt');
  FUnitMap.Add('B3', 'libra de bateo');
  FUnitMap.Add('B31', 'kilogramo metro por segundo');
  FUnitMap.Add('B32', 'kilogramo metro cuadrado');
  FUnitMap.Add('B33', 'kilogramo metro cuadrado por segundo');
  FUnitMap.Add('B34', 'kilogramo por decímetro cúbico');
  FUnitMap.Add('B35', 'kilogramo por litro');
  FUnitMap.Add('B36', 'caloría termoquímica por gramo');
  FUnitMap.Add('B37', 'kilogramo de fuerza');
  FUnitMap.Add('B38', 'metro de fuerza de kilogramo');
  FUnitMap.Add('B39', 'metro de fuerza de kilogramo por segundo');
  FUnitMap.Add('B4', 'barril, imperial');
  FUnitMap.Add('B40', 'kilogramo de fuerza por metro cuadrado');
  FUnitMap.Add('B41', 'kilojoule per kelvin');
  FUnitMap.Add('B42', 'kilojoule por kilogramo');
  FUnitMap.Add('B43', 'kilojoule por kilogramo kelvin');
  FUnitMap.Add('B44', 'kilojoule por mol');
  FUnitMap.Add('B45', 'kilomol');
  FUnitMap.Add('B46', 'kilomol por metro cúbico');
  FUnitMap.Add('B47', 'Kilonewton');
  FUnitMap.Add('B48', 'medidor de kilonewton');
  FUnitMap.Add('B49', 'kiloohm');
  FUnitMap.Add('B5', 'palanquilla');
  FUnitMap.Add('B50', 'medidor de kiloohm');
  FUnitMap.Add('B51', 'kilopond');
  FUnitMap.Add('B52', 'kilosegundo');
  FUnitMap.Add('B53', 'kilosiemens');
  FUnitMap.Add('B54', 'kilosiemens por metro');
  FUnitMap.Add('B55', 'kilovoltios por metro');
  FUnitMap.Add('B56', 'kiloveber por metro');
  FUnitMap.Add('B57', 'año luz');
  FUnitMap.Add('B58', 'litro por mol');
  FUnitMap.Add('B59', 'hora lumen');
  FUnitMap.Add('B6', 'bollo');
  FUnitMap.Add('B60', 'lumen por metro cuadrado');
  FUnitMap.Add('B61', 'lumen por vatio');
  FUnitMap.Add('B62', 'lumen segundo');
  FUnitMap.Add('B63', 'hora de lux');
  FUnitMap.Add('B64', 'lux segundo');
  FUnitMap.Add('B65', 'Maxwell');
  FUnitMap.Add('B66', 'megaamperios por metro cuadrado');
  FUnitMap.Add('B67', 'megabecquerel por kilogramo');
  FUnitMap.Add('B69', 'megacoulomb por metro cúbico');
  FUnitMap.Add('B7', 'ciclo');
  FUnitMap.Add('B70', 'megacoulomb por metro cuadrado');
  FUnitMap.Add('B71', 'megaelectronvolt');
  FUnitMap.Add('B72', 'megagramo por metro cúbico');
  FUnitMap.Add('B73', 'meganewton');
  FUnitMap.Add('B74', 'medidor de meganewton');
  FUnitMap.Add('B75', 'megaohm');
  FUnitMap.Add('B76', 'metro megaohm');
  FUnitMap.Add('B77', 'megasiemens por metro');
  FUnitMap.Add('B78', 'megavoltio');
  FUnitMap.Add('B79', 'megavolt por metro');
  FUnitMap.Add('B8', 'julios por metro cúbico');
  FUnitMap.Add('B81', 'metro recíproco cuadrado recíproco segundo');
  FUnitMap.Add('B83', 'metro a la cuarta potencia');
  FUnitMap.Add('B84', 'microamperios');
  FUnitMap.Add('B85', 'microbar');
  FUnitMap.Add('B86', 'microcoulomb');
  FUnitMap.Add('B87', 'microcoulomb por metro cúbico');
  FUnitMap.Add('B88', 'microcoulomb por metro cuadrado');
  FUnitMap.Add('B89', 'microfarada por metro');
  FUnitMap.Add('B9', 'batt');
  FUnitMap.Add('B90', 'microhenry');
  FUnitMap.Add('B91', 'microhenry por metro');
  FUnitMap.Add('B92', 'micronewton');
  FUnitMap.Add('B93', 'medidor de micronewton');
  FUnitMap.Add('B94', 'microohm');
  FUnitMap.Add('B95', 'medidor de microohmios');
  FUnitMap.Add('B96', 'micropascal');
  FUnitMap.Add('B97', 'microradiano');
  FUnitMap.Add('B98', 'microsegundo');
  FUnitMap.Add('B99', 'microsiemens');
  FUnitMap.Add('BAR', 'bar');
  FUnitMap.Add('BB', 'caja base');
  FUnitMap.Add('BD', 'tablero');
  FUnitMap.Add('SER', 'haz');
  FUnitMap.Add('BFT', 'pie de tabla');
  FUnitMap.Add('BG', 'bolso');
  FUnitMap.Add('BH', 'cepillo');
  FUnitMap.Add('BHP', 'potencia al freno');
  FUnitMap.Add('BIL', 'trillón de dólares');
  FUnitMap.Add('BJ', 'cangilón');
  FUnitMap.Add('BK', 'cesta');
  FUnitMap.Add('BL', 'bala');
  FUnitMap.Add('BLD', 'barril seco');
  FUnitMap.Add('BLL', 'barril (EE. UU.) (petróleo, etc.)');
  FUnitMap.Add('BO', 'botella');
  FUnitMap.Add('BP', 'cien pies de tabla');
  FUnitMap.Add('BQL', 'becquerel');
  FUnitMap.Add('BR', 'bar');
  FUnitMap.Add('BT', 'tornillo');
  FUnitMap.Add('BTU', 'Unidad Térmica Británica');
  FUnitMap.Add('BUA', 'bushel (EE. UU.)');
  FUnitMap.Add('BUI', 'bushel (Reino Unido)');
  FUnitMap.Add('BW', 'peso base');
  FUnitMap.Add('BX', 'caja');
  FUnitMap.Add('BZ', 'millones de BTUs');
  FUnitMap.Add('C0', 'llamada');
  FUnitMap.Add('C1', 'producto compuesto libra (peso total)');
  FUnitMap.Add('C10', 'millifarad');
  FUnitMap.Add('C11', 'miligal');
  FUnitMap.Add('C12', 'miligramo por metro');
  FUnitMap.Add('C13', 'miligray');
  FUnitMap.Add('C14', 'milihenry');
  FUnitMap.Add('C15', 'milijoule');
  FUnitMap.Add('C16', 'milímetro por segundo');
  FUnitMap.Add('C17', 'milímetro cuadrado por segundo');
  FUnitMap.Add('C18', 'milimol');
  FUnitMap.Add('C19', 'mol por kilogramo');
  FUnitMap.Add('C2', 'carset');
  FUnitMap.Add('C20', 'millinewton');
  FUnitMap.Add('C22', 'millinewton por metro');
  FUnitMap.Add('C23', 'medidor de miliohm');
  FUnitMap.Add('C24', 'segundo milipascal');
  FUnitMap.Add('C25', 'miliradian');
  FUnitMap.Add('C26', 'milisegundo');
  FUnitMap.Add('C27', 'milisiemens');
  FUnitMap.Add('C28', 'milisievert');
  FUnitMap.Add('C29', 'millitesla');
  FUnitMap.Add('C3', 'microvoltios por metro');
  FUnitMap.Add('C30', 'milivoltios por metro');
  FUnitMap.Add('C31', 'milivatios');
  FUnitMap.Add('C32', 'milivatios por metro cuadrado');
  FUnitMap.Add('C33', 'milliweber');
  FUnitMap.Add('C34', 'Topo');
  FUnitMap.Add('C35', 'mol por decímetro cúbico');
  FUnitMap.Add('C36', 'mol por metro cúbico');
  FUnitMap.Add('C38', 'mol por litro');
  FUnitMap.Add('C39', 'Nanoampere');
  FUnitMap.Add('C4', 'partido de carga');
  FUnitMap.Add('C40', 'nanocoulomb');
  FUnitMap.Add('C41', 'nanofarad');
  FUnitMap.Add('C42', 'nanofarad por metro');
  FUnitMap.Add('C43', 'nanohenry');
  FUnitMap.Add('C44', 'nanohenry por metro');
  FUnitMap.Add('C45', 'nanometro');
  FUnitMap.Add('C46', 'medidor de nanoohm');
  FUnitMap.Add('C47', 'nanosegundo');
  FUnitMap.Add('C48', 'nanotesla');
  FUnitMap.Add('C49', 'nanovatio');
  FUnitMap.Add('C5', 'costo');
  FUnitMap.Add('C50', 'neper');
  FUnitMap.Add('C51', 'neper por segundo');
  FUnitMap.Add('C52', 'picometro');
  FUnitMap.Add('C53', 'metro de newton segundo');
  FUnitMap.Add('C54', 'newton metro cuadrado kilogramo cuadrado');
  FUnitMap.Add('C55', 'newton por metro cuadrado');
  FUnitMap.Add('C56', 'newton por milímetro cuadrado');
  FUnitMap.Add('C57', 'newton segundo');
  FUnitMap.Add('C58', 'newton segundo por metro');
  FUnitMap.Add('C59', 'octava');
  FUnitMap.Add('C6', 'célula');
  FUnitMap.Add('C60', 'ohm centímetro');
  FUnitMap.Add('C61', 'ohm metro');
  FUnitMap.Add('C62', 'uno');
  FUnitMap.Add('C63', 'parsec');
  FUnitMap.Add('C64', 'pascal por kelvin');
  FUnitMap.Add('C65', 'segundo pascal');
  FUnitMap.Add('C66', 'segundo pascal por metro cúbico');
  FUnitMap.Add('C67', 'segundo pascal por metro');
  FUnitMap.Add('C68', 'petajoule');
  FUnitMap.Add('C69', 'telefono');
  FUnitMap.Add('C7', 'centipoise');
  FUnitMap.Add('C70', 'picoampere');
  FUnitMap.Add('C71', 'picocoulomb');
  FUnitMap.Add('C72', 'picofarad por metro');
  FUnitMap.Add('C73', 'picohenry');
  FUnitMap.Add('C75', 'picowatt');
  FUnitMap.Add('C76', 'picowatt por metro cuadrado');
  FUnitMap.Add('C77', 'medidor de libras');
  FUnitMap.Add('C78', 'fuerza de libra');
  FUnitMap.Add('C8', 'Millicoulomb por kilogramo');
  FUnitMap.Add('C80', 'rad');
  FUnitMap.Add('C81', 'radián');
  FUnitMap.Add('C82', 'medidor de radianes al cuadrado por mol');
  FUnitMap.Add('C83', 'medidor de radianes al cuadrado por kilogramo');
  FUnitMap.Add('C84', 'radian por metro');
  FUnitMap.Add('C85', 'â € ngstr recíproco "m');
  FUnitMap.Add('C86', 'metro cúbico recíproco');
  FUnitMap.Add('C87', 'metro cúbico recíproco por segundo');
  FUnitMap.Add('C88', 'voltios de electrones recíprocos por metro cúbico');
  FUnitMap.Add('C89', 'Henry Recíproco');
  FUnitMap.Add('C9', 'grupo de bobina');
  FUnitMap.Add('C90', 'Joule recíproco por metro cúbico');
  FUnitMap.Add('C91', 'kelvin recíproco o kelvin al poder menos uno');
  FUnitMap.Add('C92', 'medidor recíproco');
  FUnitMap.Add('C93', 'metro cuadrado recíproco');
  FUnitMap.Add('C94', 'minuto recíproco');
  FUnitMap.Add('C95', 'mole recíproco');
  FUnitMap.Add('C96', 'Pascal recíproco o pascal a la potencia menos uno.');
  FUnitMap.Add('C97', 'segundo recíproco');
  FUnitMap.Add('C98', 'segundo recíproco por metro cúbico');
  FUnitMap.Add('C99', 'segundo recíproco por metro cuadrado');
  FUnitMap.Add('CA', 'Caja');
  FUnitMap.Add('CCT', 'Capacidad de carga en toneladas métricas.');
  FUnitMap.Add('CDL', 'candela');
  FUnitMap.Add('CEL', 'grado Celsius');
  FUnitMap.Add('CEN', 'cien');
  FUnitMap.Add('CG', 'tarjeta');
  FUnitMap.Add('CGM', 'centigramo');
  FUnitMap.Add('CH', 'envase');
  FUnitMap.Add('CJ', 'cono');
  FUnitMap.Add('CK', 'conector');
  FUnitMap.Add('CKG', 'Coulomb por kilogramo');
  FUnitMap.Add('CL', 'bobina');
  FUnitMap.Add('CLF', 'cientos de licencia');
  FUnitMap.Add('CLT', 'centilitro');
  FUnitMap.Add('CMK', 'centímetro cuadrado');
  FUnitMap.Add('CMQ', 'centímetro cúbico');
  FUnitMap.Add('CMT', 'centímetro');
  FUnitMap.Add('CNP', 'paquete de cien');
  FUnitMap.Add('CNT', 'Cental (Reino Unido)');
  FUnitMap.Add('CO', 'garrafón');
  FUnitMap.Add('COU', 'culombio');
  FUnitMap.Add('CQ', 'cartucho');
  FUnitMap.Add('CR', 'caja');
  FUnitMap.Add('CS', 'caso');
  FUnitMap.Add('CT', 'caja de cartón');
  FUnitMap.Add('CTM', 'quilate métrico');
  FUnitMap.Add('CU', 'vaso');
  FUnitMap.Add('CUR', 'curie');
  FUnitMap.Add('CV', 'cubrir');
  FUnitMap.Add('CWA', 'cien libras (quintales) / cien pesos (US)');
  FUnitMap.Add('CWI', 'cien pesos (Reino Unido)');
  FUnitMap.Add('CY', 'cilindro');
  FUnitMap.Add('CZ', 'combo');
  FUnitMap.Add('D1', 'segundo recíproco por esteradiano');
  FUnitMap.Add('D10', 'siemens por metro');
  FUnitMap.Add('D12', 'siemens metro cuadrado por mol');
  FUnitMap.Add('D13', 'sievert');
  FUnitMap.Add('D14', 'mil yardas lineales');
  FUnitMap.Add('D15', 'sone');
  FUnitMap.Add('D16', 'centímetro cuadrado por ergio');
  FUnitMap.Add('D17', 'centímetro cuadrado por erg esterlina');
  FUnitMap.Add('D18', 'metro kelvin');
  FUnitMap.Add('D19', 'kelvin metro cuadrado por vatio');
  FUnitMap.Add('D2', 'segundo recíproco por metros cuadrados esteradianos');
  FUnitMap.Add('D20', 'metro cuadrado por julio');
  FUnitMap.Add('D21', 'metro cuadrado por kilogramo');
  FUnitMap.Add('D22', 'metro cuadrado por mol');
  FUnitMap.Add('D23', 'pluma gramo (proteína)');
  FUnitMap.Add('D24', 'metro cuadrado por esterilizador');
  FUnitMap.Add('D25', 'metro cuadrado por julios esteradianos');
  FUnitMap.Add('D26', 'metro cuadrado por voltio segundo');
  FUnitMap.Add('D27', 'esteradiano');
  FUnitMap.Add('D28', 'sifón');
  FUnitMap.Add('D29', 'terahercios');
  FUnitMap.Add('D30', 'terajulio');
  FUnitMap.Add('D31', 'teravatio');
  FUnitMap.Add('D32', 'hora de teravatio');
  FUnitMap.Add('D33', 'tesla');
  FUnitMap.Add('D34', 'Texas');
  FUnitMap.Add('D35', 'caloría termoquímica');
  FUnitMap.Add('D37', 'caloría termoquímica por gramo kelvin');
  FUnitMap.Add('D38', 'calorías termoquímicas por segundo centímetro kelvin');
  FUnitMap.Add('D39', 'calorías termoquímicas por segundo centímetro cuadrado kelvin');
  FUnitMap.Add('D40', 'mil litros');
  FUnitMap.Add('D41', 'tonelada por metro cúbico');
  FUnitMap.Add('D42', 'año tropical');
  FUnitMap.Add('D43', 'unidad de masa atómica unificada');
  FUnitMap.Add('D44', 'var');
  FUnitMap.Add('D45', 'voltios al cuadrado por kelvin al cuadrado');
  FUnitMap.Add('D46', 'voltio – amperio');
  FUnitMap.Add('D47', 'voltio por centímetro');
  FUnitMap.Add('D48', 'voltio por kelvin');
  FUnitMap.Add('D49', 'milivoltios por kelvin');
  FUnitMap.Add('D5', 'kilogramo por centímetro cuadrado');
  FUnitMap.Add('D50', 'voltios por metro');
  FUnitMap.Add('D51', 'voltios por milímetro');
  FUnitMap.Add('D52', 'vatios por kelvin');
  FUnitMap.Add('D53', 'vatios por metro kelvin');
  FUnitMap.Add('D54', 'vatios por metro cuadrado');
  FUnitMap.Add('D55', 'vatios por metro cuadrado kelvin');
  FUnitMap.Add('D56', 'vatios por metro cuadrado de kelvin a la cuarta potencia');
  FUnitMap.Add('D57', 'vatios por steradian');
  FUnitMap.Add('D58', 'vatios por metro cuadrado esterlino');
  FUnitMap.Add('D59', 'weber por metro');
  FUnitMap.Add('D6', 'röntgen por segundo');
  FUnitMap.Add('D60', 'weber por milímetro');
  FUnitMap.Add('D61', 'minuto');
  FUnitMap.Add('D62', 'segundo');
  FUnitMap.Add('D63', 'libro');
  FUnitMap.Add('D64', 'bloquear');
  FUnitMap.Add('D65', 'redondo');
  FUnitMap.Add('D66', 'casete');
  FUnitMap.Add('D67', 'dólar por hora');
  FUnitMap.Add('D69', 'pulgada a la cuarta potencia');
  FUnitMap.Add('D7', 'Sandwich');
  FUnitMap.Add('D70', 'Tabla Internacional (IT) caloría');
  FUnitMap.Add('D71', 'Tabla Internacional (IT) calorías por segundo centímetro kelvin');
  FUnitMap.Add('D72', 'Tabla Internacional (IT) calorías por segundo centímetro cuadrado kelvin');
  FUnitMap.Add('D73', 'joule metro cuadrado');
  FUnitMap.Add('D74', 'kilogramo por mol');
  FUnitMap.Add('D75', 'Tabla Internacional (IT) calorías por gramo');
  FUnitMap.Add('D76', 'Tabla Internacional (IT) calorías por gramo kelvin');
  FUnitMap.Add('D77', 'megacoulomb');
  FUnitMap.Add('D79', 'haz');
  FUnitMap.Add('D8', 'puntaje de drenaje');
  FUnitMap.Add('D80', 'microwatt');
  FUnitMap.Add('D81', 'microtesla');
  FUnitMap.Add('D82', 'microvoltio');
  FUnitMap.Add('D83', 'medidor de millinewton');
  FUnitMap.Add('D85', 'microwatt por metro cuadrado');
  FUnitMap.Add('D86', 'Millicoulomb');
  FUnitMap.Add('D87', 'milimol por kilogramo');
  FUnitMap.Add('D88', 'millicoulomb por metro cúbico');
  FUnitMap.Add('D89', 'millicoulomb por metro cuadrado');
  FUnitMap.Add('D9', 'dina por centímetro cuadrado');
  FUnitMap.Add('D90', 'metro cúbico (neto)');
  FUnitMap.Add('D91', 'movimiento rápido del ojo');
  FUnitMap.Add('D92', 'banda');
  FUnitMap.Add('D93', 'segundo por metro cúbico');
  FUnitMap.Add('D94', 'segundo por metro cúbico radianes');
  FUnitMap.Add('D95', 'julios por gramo');
  FUnitMap.Add('D96', 'libra bruta');
  FUnitMap.Add('D97', 'carga de palet / unidad');
  FUnitMap.Add('D98', 'libra de masa');
  FUnitMap.Add('D99', 'manga');
  FUnitMap.Add('DAA', 'despreciar');
  FUnitMap.Add('DAD', 'diez dias');
  FUnitMap.Add('DAY', 'día');
  FUnitMap.Add('DB', 'libra seca');
  FUnitMap.Add('DC', 'disco');
  FUnitMap.Add('DD', 'la licenciatura');
  FUnitMap.Add('DE', 'acuerdo');
  FUnitMap.Add('DEC', 'década');
  FUnitMap.Add('DG', 'decigramo');
  FUnitMap.Add('DI', 'dispensador');
  FUnitMap.Add('DJ', 'decagramo');
  FUnitMap.Add('DLT', 'decilitro');
  FUnitMap.Add('DMK', 'nformaci cuadrado');
  FUnitMap.Add('DMQ', 'decímetro cúbico');
  FUnitMap.Add('DMT', 'decímetro');
  FUnitMap.Add('DN', 'medidor de decinewton');
  FUnitMap.Add('DPC', 'docena pieza');
  FUnitMap.Add('DPR', 'docena par');
  FUnitMap.Add('DPT', 'tonelaje de desplazamiento');
  FUnitMap.Add('DQ', 'registro de datos');
  FUnitMap.Add('DR', 'tambor');
  FUnitMap.Add('DRA', 'dram (US)');
  FUnitMap.Add('DRI', 'dram (Reino Unido)');
  FUnitMap.Add('DRL', 'docena rollo');
  FUnitMap.Add('DRM', 'dracma (Reino Unido)');
  FUnitMap.Add('DS', 'monitor');
  FUnitMap.Add('DT', 'tonelada seca');
  FUnitMap.Add('DTN', 'Decitonne');
  FUnitMap.Add('DU', 'dina');
  FUnitMap.Add('DWT', 'pennyweight');
  FUnitMap.Add('DX', 'dina por centímetro');
  FUnitMap.Add('DY', 'libro de directorio');
  FUnitMap.Add('DZN', 'docena');
  FUnitMap.Add('DZP', 'paquete de doce');
  FUnitMap.Add('E2', 'cinturón');
  FUnitMap.Add('E3', 'remolque');
  FUnitMap.Add('E4', 'kilogramo bruto');
  FUnitMap.Add('E5', 'tonelada métrica larga');
  FUnitMap.Add('EA', 'cada');
  FUnitMap.Add('EB', 'casilla de correo electrónico');
  FUnitMap.Add('CE', 'cada uno por mes');
  FUnitMap.Add('EP', 'paquete de once');
  FUnitMap.Add('EQ', 'galón equivalente');
  FUnitMap.Add('EV', 'sobre');
  FUnitMap.Add('F1', 'mil pies cúbicos por día');
  FUnitMap.Add('F9', 'Fibra por centímetro cúbico de aire');
  FUnitMap.Add('FAH', 'grado Fahrenheit');
  FUnitMap.Add('FAR', 'faradio');
  FUnitMap.Add('FB', 'campo');
  FUnitMap.Add('FC', 'mil pies cúbicos');
  FUnitMap.Add('FD', 'millón de partículas por pie cúbico');
  FUnitMap.Add('FE', 'pie de pista');
  FUnitMap.Add('FF', 'cien metros cúbicos');
  FUnitMap.Add('FG', 'parche transdérmico');
  FUnitMap.Add('FH', 'micromol');
  FUnitMap.Add('FL', 'tonelada en escamas');
  FUnitMap.Add('FM', 'millones de pies cúbicos');
  FUnitMap.Add('FOT', 'pie');
  FUnitMap.Add('FP', 'libra por pie cuadrado');
  FUnitMap.Add('FR', 'pie por minuto');
  FUnitMap.Add('FS', 'pie por segundo');
  FUnitMap.Add('FTK', 'pie cuadrado');
  FUnitMap.Add('FTQ', 'pie cubico');
  FUnitMap.Add('G2', 'US galones por minuto');
  FUnitMap.Add('G3', 'Galon imperial por minuto');
  FUnitMap.Add('G7', 'hoja de microficha');
  FUnitMap.Add('GB', 'galón (US) por día');
  FUnitMap.Add('GBQ', 'gigabecquerel');
  FUnitMap.Add('GC', 'gramo por 100 gramo');
  FUnitMap.Add('GD', 'barril bruto');
  FUnitMap.Add('GE', 'libra por galón (US)');
  FUnitMap.Add('GF', 'gramo por metro (gramo por 100 centímetros)');
  FUnitMap.Add('GFI', 'gramo de isótopo fisionable');
  FUnitMap.Add('GGR', 'gramo');
  FUnitMap.Add('GH', 'medio galón (EE. UU.)');
  FUnitMap.Add('GIA', 'branquias');
  FUnitMap.Add('GII', 'Gill (Reino Unido)');
  FUnitMap.Add('GJ', 'gramo por mililitro');
  FUnitMap.Add('G K', 'gramo por kilogramo');
  FUnitMap.Add('GL', 'gramo por litro');
  FUnitMap.Add('GLD', 'galón seco (EE. UU.)');
  FUnitMap.Add('GLI', 'galón (Reino Unido)');
  FUnitMap.Add('GLL', 'galón');
  FUnitMap.Add('GM', 'gramo por metro cuadrado');
  FUnitMap.Add('GN', 'galón bruto');
  FUnitMap.Add('GO', 'miligramos por metro cuadrado');
  FUnitMap.Add('GP', 'miligramo por metro cúbico');
  FUnitMap.Add('GQ', 'microgramos por metro cúbico');
  FUnitMap.Add('GRM', 'gramo');
  FUnitMap.Add('GRN', 'grano');
  FUnitMap.Add('GRO', 'bruto');
  FUnitMap.Add('GRT', 'tonelada de registro bruto');
  FUnitMap.Add('GT', 'tonelada bruta');
  FUnitMap.Add('GV', 'gigajoule');
  FUnitMap.Add('GW', 'galón por mil pies cúbicos');
  FUnitMap.Add('GWH', 'hora de gigavatios');
  FUnitMap.Add('GY', 'patio bruto');
  FUnitMap.Add('GZ', 'sistema de medición');
  FUnitMap.Add('H1', 'media página – electrónica');
  FUnitMap.Add('H2', 'medio litro');
  FUnitMap.Add('HA', 'madeja');
  FUnitMap.Add('HAR', 'hectárea');
  FUnitMap.Add('HBA', 'hectobar');
  FUnitMap.Add('HBX', 'cien cajas');
  FUnitMap.Add('HC', 'cien cuentas');
  FUnitMap.Add('HD', 'media docena');
  FUnitMap.Add('ÉL', 'centésima de quilate');
  FUnitMap.Add('HF', 'cien pies');
  FUnitMap.Add('HGM', 'hectogramo');
  FUnitMap.Add('HH', 'cien pies cúbicos');
  FUnitMap.Add('HI', 'cien hojas');
  FUnitMap.Add('HIU', 'cien unidades internacionales');
  FUnitMap.Add('HJ', 'caballo métrico');
  FUnitMap.Add('HK', 'cien kilogramos');
  FUnitMap.Add('HL', 'cien pies (lineales)');
  FUnitMap.Add('HLT', 'hectolitro');
  FUnitMap.Add('HM', 'milla por hora');
  FUnitMap.Add('HMQ', 'millones de metros cúbicos');
  FUnitMap.Add('HMT', 'hectómetro');
  FUnitMap.Add('HN', 'milímetro convencional de mercurio');
  FUnitMap.Add('HO', 'cien onzas troy');
  FUnitMap.Add('HP', 'milímetro convencional de agua');
  FUnitMap.Add('HPA', 'hectolitro de alcohol puro');
  FUnitMap.Add('HS', 'cien pies cuadrados');
  FUnitMap.Add('HT', 'media hora');
  FUnitMap.Add('HTZ', 'hertz');
  FUnitMap.Add('HUR', 'hora');
  FUnitMap.Add('HY', 'cien yardas');
  FUnitMap.Add('IA', 'pulgada libra');
  FUnitMap.Add('IC', 'contar por pulgada');
  FUnitMap.Add('IE', 'persona');
  FUnitMap.Add('IF', 'pulgadas de agua');
  FUnitMap.Add('II', 'columna pulgada');
  FUnitMap.Add('IL', 'pulgada por minuto');
  FUnitMap.Add('IM', 'impresión');
  FUnitMap.Add('INH', 'pulgada');
  FUnitMap.Add('INK', 'pulgada cuadrada');
  FUnitMap.Add('INQ', 'pulgada en cubos');
  FUnitMap.Add('IP', 'póliza de seguros');
  FUnitMap.Add('IT', 'conteo por centímetro');
  FUnitMap.Add('IU', 'pulgada por segundo (velocidad lineal)');
  FUnitMap.Add('IV', 'pulgada por segundo al cuadrado (aceleración)');
  FUnitMap.Add('J2', 'julios por kilogramo');
  FUnitMap.Add('JB', 'jumbo');
  FUnitMap.Add('JE', 'joule por kelvin');
  FUnitMap.Add('JG', 'jarra');
  FUnitMap.Add('JK', 'megajulio por kilogramo');
  FUnitMap.Add('JM', 'megajulio por metro cúbico');
  FUnitMap.Add('JO', 'articulación');
  FUnitMap.Add('JOU', 'joule');
  FUnitMap.Add('JR', 'tarro');
  FUnitMap.Add('K1', 'demanda de kilovatios');
  FUnitMap.Add('K2', 'kilovoltios amperios reactivos de demanda');
  FUnitMap.Add('K3', 'kilovoltio amperio hora reactiva');
  FUnitMap.Add('K5', 'amperios kilovoltios (reactivos)');
  FUnitMap.Add('K6', 'kilolitro');
  FUnitMap.Add('KA', 'pastel');
  FUnitMap.Add('KB', 'kilocharacter');
  FUnitMap.Add('KBA', 'kilobar');
  FUnitMap.Add('KD', 'kilogramo decimal');
  FUnitMap.Add('KEL', 'kelvin');
  FUnitMap.Add('KF', 'kilopacket');
  FUnitMap.Add('KG', 'barrilete');
  FUnitMap.Add('KGM', 'kilogramo');
  FUnitMap.Add('KGS', 'kilogramo por segundo');
  FUnitMap.Add('KHZ', 'kilohercio');
  FUnitMap.Add('KI', 'Kilogramo por milímetro de ancho');
  FUnitMap.Add('KJ', 'kilosegmento');
  FUnitMap.Add('KJO', 'kilojoule');
  FUnitMap.Add('KL', 'kilogramo por metro');
  FUnitMap.Add('KMH', 'kilómetro por hora');
  FUnitMap.Add('KMK', 'kilometro cuadrado');
  FUnitMap.Add('KMQ', 'kilogramo por metro cúbico');
  FUnitMap.Add('KNI', 'kilogramo de nitrógeno');
  FUnitMap.Add('KNS', 'kilogramo de sustancia nombrada');
  FUnitMap.Add('KNT', 'nudo');
  FUnitMap.Add('KO', 'Milliequivalencia de potasa cáustica por gramo de producto.');
  FUnitMap.Add('KPA', 'kilopascal');
  FUnitMap.Add('KPH', 'kilogramo de hidróxido de potasio (potasa cáustica)');
  FUnitMap.Add('KPO', 'kilogramo de óxido de potasio');
  FUnitMap.Add('KPP', 'kilogramo de pentóxido de fósforo (anhídrido fosfórico)');
  FUnitMap.Add('KR', 'KilorÃ¶ntgen');
  FUnitMap.Add('KS', 'mil libras por pulgada cuadrada');
  FUnitMap.Add('KSD', 'kilogramo de sustancia 90% seca');
  FUnitMap.Add('KSH', 'kilogramo de hidróxido de sodio (soda cáustica)');
  FUnitMap.Add('KT', 'equipo');
  FUnitMap.Add('KTM', 'kilómetro');
  FUnitMap.Add('KTN', 'kilotonne');
  FUnitMap.Add('KUR', 'kilogramo de uranio');
  FUnitMap.Add('KVA', 'kilovoltio – ampere');
  FUnitMap.Add('KVR', 'kilovar');
  FUnitMap.Add('KVT', 'kilovoltio');
  FUnitMap.Add('KW', 'kilogramos por milímetro');
  FUnitMap.Add('KWH', 'kilovatios hora');
  FUnitMap.Add('KWT', 'kilovatio');
  FUnitMap.Add('KX', 'mililitro por kilogramo');
  FUnitMap.Add('L2', 'litro por minuto');
  FUnitMap.Add('LA', 'libra por pulgada cúbica');
  FUnitMap.Add('LBR', 'libra');
  FUnitMap.Add('LBT', 'libra troy');
  FUnitMap.Add('LC', 'centímetro lineal');
  FUnitMap.Add('LD', 'litro por día');
  FUnitMap.Add('LE', 'lite');
  FUnitMap.Add('LEF', 'hoja');
  FUnitMap.Add('LF', 'pie lineal');
  FUnitMap.Add('LH', 'hora de trabajo');
  FUnitMap.Add('LI', 'pulgada lineal');
  FUnitMap.Add('LJ', 'spray grande');
  FUnitMap.Add('LK', 'enlazar');
  FUnitMap.Add('LM', 'metro lineal');
  FUnitMap.Add('LN', 'longitud');
  FUnitMap.Add('LO', 'mucho');
  FUnitMap.Add('LP', 'libra liquida');
  FUnitMap.Add('LPA', 'litro de alcohol puro');
  FUnitMap.Add('LR', 'capa');
  FUnitMap.Add('LS', 'Suma global');
  FUnitMap.Add('LTN', 'ton (Reino Unido) o longton (EE. UU.)');
  FUnitMap.Add('LTR', 'litro');
  FUnitMap.Add('LUM', 'lumen');
  FUnitMap.Add('LUX', 'lux');
  FUnitMap.Add('LX', 'yarda lineal por libra');
  FUnitMap.Add('LY', 'yarda lineal');
  FUnitMap.Add('M0', 'cinta magnética');
  FUnitMap.Add('M1', 'miligramos por litro');
  FUnitMap.Add('M4', 'valor monetario');
  FUnitMap.Add('M5', 'microcurie');
  FUnitMap.Add('M7', 'micropulgada');
  FUnitMap.Add('M9', 'millones de Btu por 1000 pies cúbicos');
  FUnitMap.Add('MA', 'máquina por unidad');
  FUnitMap.Add('MAL', 'mega litro');
  FUnitMap.Add('MAM', 'megametro');
  FUnitMap.Add('MAW', 'megavatio');
  FUnitMap.Add('MBE', 'mil equivalentes de ladrillo estándar');
  FUnitMap.Add('MBF', 'mil pies de tabla');
  FUnitMap.Add('MBR', 'milibar');
  FUnitMap.Add('MC', 'microgramo');
  FUnitMap.Add('MCU', 'milicurie');
  FUnitMap.Add('MD', 'aire seco tonelada métrica');
  FUnitMap.Add('MF', 'miligramo por pie cuadrado por lado');
  FUnitMap.Add('MG', 'miligramo');
  FUnitMap.Add('MHZ', 'megahercio');
  FUnitMap.Add('MIK', 'milla cuadrada');
  FUnitMap.Add('MIL', 'mil');
  FUnitMap.Add('MIN', 'minuto');
  FUnitMap.Add('MIO', 'millón');
  FUnitMap.Add('MIU', 'millones de unidades internacionales');
  FUnitMap.Add('MK', 'miligramo por pulgada cuadrada');
  FUnitMap.Add('MLD', 'mil millones');
  FUnitMap.Add('MLT', 'mililitro');
  FUnitMap.Add('MMK', 'milímetro cuadrado');
  FUnitMap.Add('MMQ', 'milímetro cúbico');
  FUnitMap.Add('MMT', 'milímetro');
  FUnitMap.Add('LUN', 'mes');
  FUnitMap.Add('MPA', 'megapascal');
  FUnitMap.Add('MQ', 'mil metros');
  FUnitMap.Add('MQH', 'metro cúbico por hora');
  FUnitMap.Add('MQS', 'metro cúbico por segundo');
  FUnitMap.Add('MSK', 'metro por segundo al cuadrado');
  FUnitMap.Add('MT', 'estera');
  FUnitMap.Add('MTK', 'metro cuadrado');
  FUnitMap.Add('MTQ', 'Metro cúbico');
  FUnitMap.Add('MTR', 'metro');
  FUnitMap.Add('MTS', 'metro por segundo');
  FUnitMap.Add('MV', 'numero de mults');
  FUnitMap.Add('MVA', 'megavolt – ampere');
  FUnitMap.Add('MWH', 'megavatios hora (1000 kW.h)');
  FUnitMap.Add('N1', 'calorías de la pluma');
  FUnitMap.Add('N2', 'número de líneas');
  FUnitMap.Add('N3', 'punto de impresión');
  FUnitMap.Add('NA', 'miligramo por kilogramo');
  FUnitMap.Add('NAR', 'número de artículos');
  FUnitMap.Add('NB', 'barcaza');
  FUnitMap.Add('NBB', 'número de bobinas');
  FUnitMap.Add('NC', 'coche');
  FUnitMap.Add('NCL', 'número de celdas');
  FUnitMap.Add('ND', 'barril neto');
  FUnitMap.Add('NE', 'litro neto');
  FUnitMap.Add('NEW', 'newton');
  FUnitMap.Add('NF', 'mensaje');
  FUnitMap.Add('NG', 'galón neto (nosotros)');
  FUnitMap.Add('NH', 'hora del mensaje');
  FUnitMap.Add('NI', 'galón imperial neto');
  FUnitMap.Add('NIU', 'número de unidades internacionales');
  FUnitMap.Add('NJ', 'número de pantallas');
  FUnitMap.Add('NL', 'carga');
  FUnitMap.Add('MNI', 'milla nautica');
  FUnitMap.Add('NMP', 'número de paquetes');
  FUnitMap.Add('NN', 'entrenar');
  FUnitMap.Add('NPL', 'número de parcelas');
  FUnitMap.Add('NPR', 'numero de pares');
  FUnitMap.Add('TNP', 'numero de partes');
  FUnitMap.Add('NQ', 'mho');
  FUnitMap.Add('NR', 'micromho');
  FUnitMap.Add('NRL', 'número de rollos');
  FUnitMap.Add('NT', 'tonelada neta');
  FUnitMap.Add('NTT', 'registro neto de toneladas');
  FUnitMap.Add('NU', 'medidor de newton');
  FUnitMap.Add('NV', 'vehículo');
  FUnitMap.Add('NX', 'parte por mil');
  FUnitMap.Add('NY', 'libra por aire seco tonelada métrica');
  FUnitMap.Add('OA', 'panel');
  FUnitMap.Add('OHM', 'ohm');
  FUnitMap.Add('EN', 'onza por yarda cuadrada');
  FUnitMap.Add('ONZ', 'onza');
  FUnitMap.Add('OP', 'Dos paquetes');
  FUnitMap.Add('OT', 'hora extra');
  FUnitMap.Add('ONZ', 'onza av');
  FUnitMap.Add('OZA', 'onza líquida (US)');
  FUnitMap.Add('OZI', 'onza líquida (Reino Unido)');
  FUnitMap.Add('P0', 'pagina – electronica');
  FUnitMap.Add('P1', 'por ciento');
  FUnitMap.Add('P2', 'libra por pie');
  FUnitMap.Add('P3', 'paquete de tres');
  FUnitMap.Add('P4', 'paquete de cuatro');
  FUnitMap.Add('P5', 'paquete de cinco');
  FUnitMap.Add('P6', 'paquete de seis');
  FUnitMap.Add('P7', 'paquete de siete');
  FUnitMap.Add('P8', 'paquete de ocho');
  FUnitMap.Add('P9', 'paquete de nueve');
  FUnitMap.Add('PA', 'paquete');
  FUnitMap.Add('PAL', 'pascal');
  FUnitMap.Add('PB', 'par de pulgadas');
  FUnitMap.Add('PD', 'almohadilla');
  FUnitMap.Add('PE', 'equivalente en libras');
  FUnitMap.Add('PF', 'palet (ascensor)');
  FUnitMap.Add('PG', 'plato');
  FUnitMap.Add('PGL', 'galón de prueba');
  FUnitMap.Add('Pi', 'tono');
  FUnitMap.Add('PK', 'paquete');
  FUnitMap.Add('PL', 'cubo');
  FUnitMap.Add('PM', 'porcentaje de libra');
  FUnitMap.Add('PN', 'libra neta');
  FUnitMap.Add('PO', 'libra por pulgada de longitud');
  FUnitMap.Add('PQ', 'página por pulgada');
  FUnitMap.Add('PR', 'par');
  FUnitMap.Add('PD', 'fuerza de libra por pulgada cuadrada');
  FUnitMap.Add('PT', 'pinta');
  FUnitMap.Add('PTD', 'pinta seca');
  FUnitMap.Add('PTI', 'pinta (Reino Unido)');
  FUnitMap.Add('PTL', 'pinta liquida (US)');
  FUnitMap.Add('PU', 'bandeja / paquete de bandeja');
  FUnitMap.Add('PV', 'media pinta (US)');
  FUnitMap.Add('PW', 'libra por pulgada de ancho');
  FUnitMap.Add('PY', 'Peck Dry (US)');
  FUnitMap.Add('PZ', 'Peck Dry (Reino Unido)');
  FUnitMap.Add('Q3', 'comida');
  FUnitMap.Add('QA', 'página – facsímil');
  FUnitMap.Add('QAN', 'cuarto (de un año)');
  FUnitMap.Add('QB', 'página – copia impresa');
  FUnitMap.Add('QD', 'cuarto de docena');
  FUnitMap.Add('QH', 'un cuarto de hora');
  FUnitMap.Add('QK', 'cuarto de kilogramo');
  FUnitMap.Add('QR', 'mano de papel');
  FUnitMap.Add('QT', 'cuarto de galón (US)');
  FUnitMap.Add('QTD', 'cuarto seco (EE. UU.)');
  FUnitMap.Add('QTI', 'cuarto de galón (Reino Unido)');
  FUnitMap.Add('QTL', 'cuarto líquido (US)');
  FUnitMap.Add('QTR', 'cuarto (UK)');
  FUnitMap.Add('R1', 'pica');
  FUnitMap.Add('R4', 'caloría');
  FUnitMap.Add('R9', 'mil metros cúbicos');
  FUnitMap.Add('RA', 'estante');
  FUnitMap.Add('RD', 'barra');
  FUnitMap.Add('RG', 'anillo');
  FUnitMap.Add('RH', 'hora de funcionamiento o de funcionamiento');
  FUnitMap.Add('RK', 'medida métrica rollo');
  FUnitMap.Add('RL', 'carrete');
  FUnitMap.Add('RM', 'resma');
  FUnitMap.Add('RN', 'medida métrica de resma');
  FUnitMap.Add('RO', 'rodar');
  FUnitMap.Add('RP', 'libra por resma');
  FUnitMap.Add('RPM', 'revoluciones por minuto');
  FUnitMap.Add('RPS', 'revoluciones por segundo');
  FUnitMap.Add('RS', 'Reiniciar');
  FUnitMap.Add('RT', 'ingreso tonelada milla');
  FUnitMap.Add('RU', 'correr');
  FUnitMap.Add('S3', 'pie cuadrado por segundo');
  FUnitMap.Add('S4', 'metro cuadrado por segundo');
  FUnitMap.Add('S5', 'sesenta cuartos de pulgada');
  FUnitMap.Add('S6', 'sesión');
  FUnitMap.Add('S7', 'unidad de almacenamiento');
  FUnitMap.Add('S8', 'unidad de publicidad estándar');
  FUnitMap.Add('SA', 'saco');
  FUnitMap.Add('SAN', 'medio año (6 meses)');
  FUnitMap.Add('OCS', 'Puntuación');
  FUnitMap.Add('SCR', 'escrúpulo');
  FUnitMap.Add('SD', 'libra solida');
  FUnitMap.Add('SE', 'sección');
  FUnitMap.Add('SEC', 'segundo');
  FUnitMap.Add('SET', 'conjunto');
  FUnitMap.Add('SG', 'segmento');
  FUnitMap.Add('SHT', 'tonelada de envío');
  FUnitMap.Add('SIE', 'siemens');
  FUnitMap.Add('SK', 'camión cisterna dividido');
  FUnitMap.Add('SL', 'hoja de deslizamiento');
  FUnitMap.Add('SMI', 'milla (milla estatutaria)');
  FUnitMap.Add('SN', 'varilla cuadrada');
  FUnitMap.Add('SO', 'carrete');
  FUnitMap.Add('SP', 'paquete de estante');
  FUnitMap.Add('SQ', 'cuadrado');
  FUnitMap.Add('SR', 'tira');
  FUnitMap.Add('SS', 'hoja métrica medida');
  FUnitMap.Add('SST', 'corto estándar (7200 partidos)');
  FUnitMap.Add('ST', 'hoja');
  FUnitMap.Add('ITS', 'piedra (Reino Unido)');
  FUnitMap.Add('STN', 'tonelada (US) o tonelada corta (UK / US)');
  FUnitMap.Add('SV', 'patinar');
  FUnitMap.Add('SO', 'madeja');
  FUnitMap.Add('SX', 'envío');
  FUnitMap.Add('T0', 'Línea de telecomunicaciones en servicio.');
  FUnitMap.Add('T1', 'mil libras brutas');
  FUnitMap.Add('T3', 'mil piezas');
  FUnitMap.Add('T4', 'bolsa de mil');
  FUnitMap.Add('T5', 'caja de mil');
  FUnitMap.Add('T6', 'mil galones (US)');
  FUnitMap.Add('T7', 'mil impresiones');
  FUnitMap.Add('T8', 'mil pulgadas lineales');
  FUnitMap.Add('TA', 'décimo pie cúbico');
  FUnitMap.Add('TAH', 'Kiloampere hora (mil amperios hora)');
  FUnitMap.Add('TC', 'camion');
  FUnitMap.Add('TD', 'termia');
  FUnitMap.Add('TE', 'totalizador');
  FUnitMap.Add('TF', 'diez metros cuadrados');
  FUnitMap.Add('TI', 'mil pulgadas cuadradas');
  FUnitMap.Add('TJ', 'mil centímetros cuadrados');
  FUnitMap.Add('TK', 'tanque, rectangular');
  FUnitMap.Add('TL', 'mil pies (lineales)');
  FUnitMap.Add('TN', 'estaño');
  FUnitMap.Add('TNE', 'tonelada (tonelada métrica)');
  FUnitMap.Add('TP', 'paquete de diez');
  FUnitMap.Add('TPR', 'diez pares');
  FUnitMap.Add('TQ', 'mil pies');
  FUnitMap.Add('TQD', 'mil metros cúbicos por día');
  FUnitMap.Add('TR', 'diez pies cuadrados');
  FUnitMap.Add('TRL', 'trillón (EUR)');
  FUnitMap.Add('TS', 'mil pies cuadrados');
  FUnitMap.Add('TSD', 'tonelada de sustancia 90% seca');
  FUnitMap.Add('TSH', 'tonelada de vapor por hora');
  FUnitMap.Add('TT', 'mil metros lineales');
  FUnitMap.Add('TU', 'tubo');
  FUnitMap.Add('TV', 'mil kilogramos');
  FUnitMap.Add('TW', 'mil hojas');
  FUnitMap.Add('TY', 'tanque, cilíndrico');
  FUnitMap.Add('U1', 'tratamiento');
  FUnitMap.Add('U2', 'tableta');
  FUnitMap.Add('UA', 'torr');
  FUnitMap.Add('UB', 'Línea de telecomunicaciones en servicio promedio.');
  FUnitMap.Add('UC', 'puerto de telecomunicaciones');
  FUnitMap.Add('UD', 'décimo minuto');
  FUnitMap.Add('UE', 'décima hora');
  FUnitMap.Add('UF', 'uso por línea de telecomunicación promedio');
  FUnitMap.Add('UH', 'diez mil yardas');
  FUnitMap.Add('UM', 'millones de unidades');
  FUnitMap.Add('VA', 'voltio amperio por kilogramo');
  FUnitMap.Add('VI', 'frasco');
  FUnitMap.Add('VLT', 'voltio');
  FUnitMap.Add('VQ', 'abultar');
  FUnitMap.Add('VS', 'visitar');
  FUnitMap.Add('W2', 'kilo mojado');
  FUnitMap.Add('W4', 'dos semanas');
  FUnitMap.Add('WA', 'vatio por kilogramo');
  FUnitMap.Add('WB', 'libra mojada');
  FUnitMap.Add('WCD', 'cable');
  FUnitMap.Add('WE', 'tonelada mojada');
  FUnitMap.Add('WEB', 'weber');
  FUnitMap.Add('WEE', 'semana');
  FUnitMap.Add('WG', 'galon de vino');
  FUnitMap.Add('WH', 'rueda');
  FUnitMap.Add('WHR', 'vatios hora');
  FUnitMap.Add('WI', 'peso por pulgada cuadrada');
  FUnitMap.Add('WM', 'mes de trabajo');
  FUnitMap.Add('WR', 'envolver');
  FUnitMap.Add('WSD', 'estándar');
  FUnitMap.Add('WTT', 'vatio');
  FUnitMap.Add('WW', 'mililitro de agua');
  FUnitMap.Add('X1', 'cadena');
  FUnitMap.Add('YDK', 'yarda cuadrada');
  FUnitMap.Add('YDQ', 'Yarda cúbica');
  FUnitMap.Add('YL', 'cien yardas lineales');
  FUnitMap.Add('YRD', 'yarda');
  FUnitMap.Add('YT', 'diez yardas');
  FUnitMap.Add('Z1', 'van de elevación');
  FUnitMap.Add('Z2', 'pecho');
  FUnitMap.Add('Z3', 'barril');
  FUnitMap.Add('Z4', 'pipa');
  FUnitMap.Add('Z5', 'arrastrar');
  FUnitMap.Add('Z6', 'punto de conferencia');
  FUnitMap.Add('Z8', 'línea de noticias de ágata');
  FUnitMap.Add('ZP', 'página');
  FUnitMap.Add('ZZ', 'mutuamente definido');
end;

class destructor TDianUnits.Destroy;
begin
  FUnitMap.Free;
  inherited;
end;

class function TDianUnits.GetUnitName(const ACode: string): string;
begin
  if not FUnitMap.TryGetValue(ACode, Result) then
    Result := ACode;
end;

class function TDianUnits.Exists(const ACode: string): Boolean;
begin
  Result := FUnitMap.ContainsKey(ACode);
end;

end.
